////
////  EmojiList.swift
////  Recovery Birthdays
////
////  Created by Kurt on 20/09/2021.
////  Copyright © 2021 Kurt. All rights reserved.
////
//
//import Foundation
//
//struct EmojiList {
//    let emojiList = [
//        ["😀","Grinning Face","Smileys"],
//        ["😃","Grinning Face with Big Eyes","Smileys"],
//        ["😄","Grinning Face with Smiling Eyes","Smileys"],
//        ["😁","Beaming Face with Smiling Eyes","Smileys"],
//        ["😆","Grinning Squinting Face","Smileys"],
//        ["😅","Grinning Face with Sweat","Smileys"],
//        ["🤣","Rolling on the Floor Laughing","Smileys"],
//        ["😂","Face with Tears of Joy","Smileys"],
//        ["🙂","Slightly Smiling Face","Smileys"],
//        ["🙃","Upside-Down Face","Smileys"],
//        ["🫠","Melting Face","Smileys"],
//        ["😉","Winking Face","Smileys"],
//        ["😊","Smiling Face with Smiling Eyes","Smileys"],
//        ["😇","Smiling Face with Halo","Smileys"],
//        ["🥰","Smiling Face with Hearts","Smileys"],
//        ["😍","Smiling Face with Heart-Eyes","Smileys"],
//        ["🤩","Star-Struck","Smileys"],
//        ["😘","Face Blowing a Kiss","Smileys"],
//        ["😗","Kissing Face","Smileys"],
//        ["☺️","Smiling Face","Smileys"],
//        ["😚","Kissing Face with Closed Eyes","Smileys"],
//        ["😙","Kissing Face with Smiling Eyes","Smileys"],
//        ["🥲","Smiling Face with Tear","Smileys"],
//        ["😋","Face Savoring Food","Smileys"],
//        ["😛","Face with Tongue","Smileys"],
//        ["😜","Winking Face with Tongue","Smileys"],
//        ["🤪","Zany Face","Smileys"],
//        ["😝","Squinting Face with Tongue","Smileys"],
//        ["🤑","Money-Mouth Face","Smileys"],
//        ["🤗","Smiling Face with Open Hands","Smileys"],
//        ["🤭","Face with Hand Over Mouth","Smileys"],
//        ["🫢","Face with Open Eyes and Hand Over Mouth","Smileys"],
//        ["🫣","Face with Peeking Eye","Smileys"],
//        ["🤫","Shushing Face","Smileys"],
//        ["🤔","Thinking Face","Smileys"],
//        ["🫡","Saluting Face","Smileys"],
//        ["🤐","Zipper-Mouth Face","Smileys"],
//        ["🤨","Face with Raised Eyebrow","Smileys"],
//        ["😐","Neutral Face","Smileys"],
//        ["😑","Expressionless Face","Smileys"],
//        ["😶","Face Without Mouth","Smileys"],
//        ["🫥","Dotted Line Face","Smileys"],
//        ["😶‍🌫️","Face in Clouds","Smileys"],
//        ["😏","Smirking Face","Smileys"],
//        ["😒","Unamused Face","Smileys"],
//        ["🙄","Face with Rolling Eyes","Smileys"],
//        ["😬","Grimacing Face","Smileys"],
//        ["😮‍💨","Face Exhaling","Smileys"],
//        ["🤥","Lying Face","Smileys"],
//        ["😌","Relieved Face","Smileys"],
//        ["😔","Pensive Face","Smileys"],
//        ["😪","Sleepy Face","Smileys"],
//        ["🤤","Drooling Face","Smileys"],
//        ["😴","Sleeping Face","Smileys"],
//        ["😷","Face with Medical Mask","Smileys"],
//        ["🤒","Face with Thermometer","Smileys"],
//        ["🤕","Face with Head-Bandage","Smileys"],
//        ["🤢","Nauseated Face","Smileys"],
//        ["🤮","Face Vomiting","Smileys"],
//        ["🤧","Sneezing Face","Smileys"],
//        ["🥵","Hot Face","Smileys"],
//        ["🥶","Cold Face","Smileys"],
//        ["🥴","Woozy Face","Smileys"],
//        ["😵","Face with Crossed-Out Eyes","Smileys"],
//        ["😵‍💫","Face with Spiral Eyes","Smileys"],
//        ["🤯","Exploding Head","Smileys"],
//        ["🤠","Cowboy Hat Face","Smileys"],
//        ["🥳","Partying Face","Smileys"],
//        ["🥸","Disguised Face","Smileys"],
//        ["😎","Smiling Face with Sunglasses","Smileys"],
//        ["🤓","Nerd Face","Smileys"],
//        ["🧐","Face with Monocle","Smileys"],
//        ["😕","Confused Face","Smileys"],
//        ["🫤","Face with Diagonal Mouth","Smileys"],
//        ["😟","Worried Face","Smileys"],
//        ["🙁","Slightly Frowning Face","Smileys"],
//        ["☹️","Frowning Face","Smileys"],
//        ["😮","Face with Open Mouth","Smileys"],
//        ["😯","Hushed Face","Smileys"],
//        ["😲","Astonished Face","Smileys"],
//        ["😳","Flushed Face","Smileys"],
//        ["🥺","Pleading Face","Smileys"],
//        ["🥹","Face Holding Back Tears","Smileys"],
//        ["😦","Frowning Face with Open Mouth","Smileys"],
//        ["😧","Anguished Face","Smileys"],
//        ["😨","Fearful Face","Smileys"],
//        ["😰","Anxious Face with Sweat","Smileys"],
//        ["😥","Sad but Relieved Face","Smileys"],
//        ["😢","Crying Face","Smileys"],
//        ["😭","Loudly Crying Face","Smileys"],
//        ["😱","Face Screaming in Fear","Smileys"],
//        ["😖","Confounded Face","Smileys"],
//        ["😣","Persevering Face","Smileys"],
//        ["😞","Disappointed Face","Smileys"],
//        ["😓","Downcast Face with Sweat","Smileys"],
//        ["😩","Weary Face","Smileys"],
//        ["😫","Tired Face","Smileys"],
//        ["🥱","Yawning Face","Smileys"],
//        ["😤","Face with Steam From Nose","Smileys"],
//        ["😡","Enraged Face","Smileys"],
//        ["😠","Angry Face","Smileys"],
//        ["🤬","Face with Symbols on Mouth","Smileys"],
//        ["😈","Smiling Face with Horns, Devil","Smileys"],
//        ["👿","Angry Face with Horns, Devil","Smileys"],
//        ["💀","Skull","Smileys"],
//        ["☠️","Skull and Crossbones","Smileys"],
//        ["💩","Pile of Poo, Poop","Smileys"],
//        ["🤡","Clown Face","Smileys"],
//        ["👹","Ogre","Smileys"],
//        ["👺","Goblin","Smileys"],
//        ["👻","Ghost","Smileys"],
//        ["👽","Alien","Smileys"],
//        ["👾","Alien Monster","Smileys"],
//        ["🤖","Robot","Smileys"],
//        ["😺","Grinning Cat","Smileys"],
//        ["😸","Grinning Cat with Smiling Eyes","Smileys"],
//        ["😹","Cat with Tears of Joy","Smileys"],
//        ["😻","Smiling Cat with Heart-Eyes","Smileys"],
//        ["😼","Cat with Wry Smile","Smileys"],
//        ["😽","Kissing Cat","Smileys"],
//        ["🙀","Weary Cat","Smileys"],
//        ["😿","Crying Cat","Smileys"],
//        ["😾","Pouting Cat","Smileys"],
//        ["💋","Kiss Mark","Smileys"],
//        ["👶","Baby","People"],
//        ["🧒","Child","People"],
//        ["👦","Boy","People"],
//        ["👧","Girl","People"],
//        ["🧑","Person","People"],
//        ["👱","Person: Blond Hair","People"],
//        ["👨","Man","People"],
//        ["🧔","Person: Beard","People"],
//        ["👨‍🦰","Man: Red Hair","People"],
//        ["👨‍🦱","Man: Curly Hair","People"],
//        ["👨‍🦳","Man: White Hair","People"],
//        ["👨‍🦲","Man: Bald","People"],
//        ["👩","Woman","People"],
//        ["👩‍🦰","Woman: Red Hair","People"],
//        ["🧑‍🦰","Person: Red Hair","People"],
//        ["👩‍🦱","Woman: Curly Hair","People"],
//        ["🧑‍🦱","Person: Curly Hair","People"],
//        ["👩‍🦳","Woman: White Hair","People"],
//        ["🧑‍🦳","Person: White Hair","People"],
//        ["👩‍🦲","Woman: Bald","People"],
//        ["🧑‍🦲","Person: Bald","People"],
//        ["👱‍♀️","Woman: Blond Hair","People"],
//        ["👱‍♂️","Man: Blond Hair","People"],
//        ["🧓","Older Person","People"],
//        ["👴","Old Man","People"],
//        ["👵","Old Woman","People"],
//        ["🙍","Person Frowning","People"],
//        ["🙍‍♂️","Man Frowning","People"],
//        ["🙍‍♀️","Woman Frowning","People"],
//        ["🙎","Person Pouting","People"],
//        ["🙎‍♂️","Man Pouting","People"],
//        ["🙎‍♀️","Woman Pouting","People"],
//        ["🙅","Person Gesturing No","People"],
//        ["🙅‍♂️","Man Gesturing No","People"],
//        ["🙅‍♀️","Woman Gesturing No","People"],
//        ["🙆","Person Gesturing OK","People"],
//        ["🙆‍♂️","Man Gesturing OK","People"],
//        ["🙆‍♀️","Woman Gesturing OK","People"],
//        ["💁","Person Tipping Hand","People"],
//        ["💁‍♂️","Man Tipping Hand","People"],
//        ["💁‍♀️","Woman Tipping Hand","People"],
//        ["🙋","Person Raising Hand","People"],
//        ["🙋‍♂️","Man Raising Hand","People"],
//        ["🙋‍♀️","Woman Raising Hand","People"],
//        ["🧏","Deaf Person","People"],
//        ["🧏‍♂️","Deaf Man","People"],
//        ["🧏‍♀️","Deaf Woman","People"],
//        ["🙇","Person Bowing","People"],
//        ["🙇‍♂️","Man Bowing","People"],
//        ["🙇‍♀️","Woman Bowing","People"],
//        ["🤦","Person Facepalming","People"],
//        ["🤦‍♂️","Man Facepalming","People"],
//        ["🤦‍♀️","Woman Facepalming","People"],
//        ["🤷","Person Shrugging","People"],
//        ["🤷‍♂️","Man Shrugging","People"],
//        ["🤷‍♀️","Woman Shrugging","People"],
//        ["🧑‍⚕️","Health Worker","People"],
//        ["👨‍⚕️","Man Health Worker","People"],
//        ["👩‍⚕️","Woman Health Worker","People"],
//        ["🧑‍🎓","Student","People"],
//        ["👨‍🎓","Man Student","People"],
//        ["👩‍🎓","Woman Student","People"],
//        ["🧑‍🏫","Teacher","People"],
//        ["👨‍🏫","Man Teacher","People"],
//        ["👩‍🏫","Woman Teacher","People"],
//        ["🧑‍⚖️","Judge","People"],
//        ["👨‍⚖️","Man Judge","People"],
//        ["👩‍⚖️","Woman Judge","People"],
//        ["🧑‍🌾","Farmer","People"],
//        ["👨‍🌾","Man Farmer","People"],
//        ["👩‍🌾","Woman Farmer","People"],
//        ["🧑‍🍳","Cook","People"],
//        ["👨‍🍳","Man Cook","People"],
//        ["👩‍🍳","Woman Cook","People"],
//        ["🧑‍🔧","Mechanic","People"],
//        ["👨‍🔧","Man Mechanic","People"],
//        ["👩‍🔧","Woman Mechanic","People"],
//        ["🧑‍🏭","Factory Worker","People"],
//        ["👨‍🏭","Man Factory Worker","People"],
//        ["👩‍🏭","Woman Factory Worker","People"],
//        ["🧑‍💼","Office Worker","People"],
//        ["👨‍💼","Man Office Worker","People"],
//        ["👩‍💼","Woman Office Worker","People"],
//        ["🧑‍🔬","Scientist","People"],
//        ["👨‍🔬","Man Scientist","People"],
//        ["👩‍🔬","Woman Scientist","People"],
//        ["🧑‍💻","Technologist","People"],
//        ["👨‍💻","Man Technologist","People"],
//        ["👩‍💻","Woman Technologist","People"],
//        ["🧑‍🎤","Singer","People"],
//        ["👨‍🎤","Man Singer","People"],
//        ["👩‍🎤","Woman Singer","People"],
//        ["🧑‍🎨","Artist","People"],
//        ["👨‍🎨","Man Artist","People"],
//        ["👩‍🎨","Woman Artist","People"],
//        ["🧑‍✈️","Pilot","People"],
//        ["👨‍✈️","Man Pilot","People"],
//        ["👩‍✈️","Woman Pilot","People"],
//        ["🧑‍🚀","Astronaut","People"],
//        ["👨‍🚀","Man Astronaut","People"],
//        ["👩‍🚀","Woman Astronaut","People"],
//        ["🧑‍🚒","Firefighter","People"],
//        ["👨‍🚒","Man Firefighter","People"],
//        ["👩‍🚒","Woman Firefighter","People"],
//        ["👮","Police Officer","People"],
//        ["👮‍♂️","Man Police Officer","People"],
//        ["👮‍♀️","Woman Police Officer","People"],
//        ["🕵️","Detective","People"],
//        ["🕵️‍♂️","Man Detective","People"],
//        ["🕵️‍♀️","Woman Detective","People"],
//        ["💂","Guard","People"],
//        ["💂‍♂️","Man Guard","People"],
//        ["💂‍♀️","Woman Guard","People"],
//        ["🥷","Ninja","People"],
//        ["👷","Construction Worker","People"],
//        ["👷‍♂️","Man Construction Worker","People"],
//        ["👷‍♀️","Woman Construction Worker","People"],
//        ["🫅","Person with Crown","People"],
//        ["🤴","Prince","People"],
//        ["👸","Princess","People"],
//        ["👳","Person Wearing Turban","People"],
//        ["👳‍♂️","Man Wearing Turban","People"],
//        ["👳‍♀️","Woman Wearing Turban","People"],
//        ["👲","Person with Skullcap","People"],
//        ["🧕","Woman with Headscarf","People"],
//        ["🤵","Person in Tuxedo","People"],
//        ["🤵‍♂️","Man in Tuxedo","People"],
//        ["🤵‍♀️","Woman in Tuxedo","People"],
//        ["👰","Person with Veil","People"],
//        ["👰‍♂️","Man with Veil","People"],
//        ["👰‍♀️","Woman with Veil","People"],
//        ["🤰","Pregnant Woman","People"],
//        ["🫃","Pregnant Man","People"],
//        ["🫄","Pregnant Person","People"],
//        ["🤱","Breast-Feeding","People"],
//        ["👩‍🍼","Woman Feeding Baby","People"],
//        ["👨‍🍼","Man Feeding Baby","People"],
//        ["🧑‍🍼","Person Feeding Baby","People"],
//        ["👼","Baby Angel","People"],
//        ["🎅","Santa Claus","People"],
//        ["🤶","Mrs. Claus","People"],
//        ["🧑‍🎄","Mx Claus","People"],
//        ["🦸","Superhero","People"],
//        ["🦸‍♂️","Man Superhero","People"],
//        ["🦸‍♀️","Woman Superhero","People"],
//        ["🦹","Supervillain","People"],
//        ["🦹‍♂️","Man Supervillain","People"],
//        ["🦹‍♀️","Woman Supervillain","People"],
//        ["🧙","Mage","People"],
//        ["🧙‍♂️","Man Mage","People"],
//        ["🧙‍♀️","Woman Mage","People"],
//        ["🧚","Fairy","People"],
//        ["🧚‍♂️","Man Fairy","People"],
//        ["🧚‍♀️","Woman Fairy","People"],
//        ["🧛","Vampire","People"],
//        ["🧛‍♂️","Man Vampire","People"],
//        ["🧛‍♀️","Woman Vampire","People"],
//        ["🧜","Merperson","People"],
//        ["🧜‍♂️","Merman","People"],
//        ["🧜‍♀️","Mermaid","People"],
//        ["🧝","Elf","People"],
//        ["🧝‍♂️","Man Elf","People"],
//        ["🧝‍♀️","Woman Elf","People"],
//        ["🧞","Genie","People"],
//        ["🧞‍♂️","Man Genie","People"],
//        ["🧞‍♀️","Woman Genie","People"],
//        ["🧟","Zombie","People"],
//        ["🧟‍♂️","Man Zombie","People"],
//        ["🧟‍♀️","Woman Zombie","People"],
//        ["🧌","Troll","People"],
//        ["💆","Person Getting Massage","People"],
//        ["💆‍♂️","Man Getting Massage","People"],
//        ["💆‍♀️","Woman Getting Massage","People"],
//        ["💇","Person Getting Haircut","People"],
//        ["💇‍♂️","Man Getting Haircut","People"],
//        ["💇‍♀️","Woman Getting Haircut","People"],
//        ["🚶","Person Walking","People"],
//        ["🚶‍♂️","Man Walking","People"],
//        ["🚶‍♀️","Woman Walking","People"],
//        ["🧍","Person Standing","People"],
//        ["🧍‍♂️","Man Standing","People"],
//        ["🧍‍♀️","Woman Standing","People"],
//        ["🧎","Person Kneeling","People"],
//        ["🧎‍♂️","Man Kneeling","People"],
//        ["🧎‍♀️","Woman Kneeling","People"],
//        ["🧑‍🦯","Person with White Cane","People"],
//        ["👨‍🦯","Man with White Cane","People"],
//        ["👩‍🦯","Woman with White Cane","People"],
//        ["🧑‍🦼","Person in Motorized Wheelchair","People"],
//        ["👨‍🦼","Man in Motorized Wheelchair","People"],
//        ["👩‍🦼","Woman in Motorized Wheelchair","People"],
//        ["🧑‍🦽","Person in Manual Wheelchair","People"],
//        ["👨‍🦽","Man in Manual Wheelchair","People"],
//        ["👩‍🦽","Woman in Manual Wheelchair","People"],
//        ["🕴️","Person in Suit Levitating","People"],
//        ["🧖","Person in Steamy Room","People"],
//        ["🧖‍♂️","Man in Steamy Room","People"],
//        ["🧖‍♀️","Woman in Steamy Room","People"],
//        ["🧑‍🤝‍🧑","People Holding Hands","People"],
//        ["👭","Women Holding Hands","People"],
//        ["👫","Woman and Man Holding Hands","People"],
//        ["👬","Men Holding Hands","People"],
//        ["👩‍❤️‍💋‍👨","Kiss: woman, man, couple with heart","People"],
//        ["👨‍❤️‍💋‍👨","Kiss: man, man, couple with heart","People"],
//        ["👩‍❤️‍💋‍👩","Kiss: woman, woman, couple with heart","People"],
//        ["🗣️","Speaking Head","People"],
//        ["👤","Bust in Silhouette","People"],
//        ["👥","Busts in Silhouette","People"],
//        ["🫂","People Hugging","People"],
//        ["🏃","Person Running","Activity"],
//        ["🏃‍♂️","Man Running","Activity"],
//        ["🏃‍♀️","Woman Running","Activity"],
//        ["💃","Woman Dancing","Activity"],
//        ["🕺","Man Dancing","Activity"],
//        ["🧗","Person Climbing","Activity"],
//        ["🧗‍♂️","Man Climbing","Activity"],
//        ["🧗‍♀️","Woman Climbing","Activity"],
//        ["🤺","Person Fencing","Activity"],
//        ["🏇","Horse Racing","Activity"],
//        ["⛷️","Skier","Activity"],
//        ["🏂","Snowboarder","Activity"],
//        ["🏌️","Person Golfing","Activity"],
//        ["🏌️‍♂️","Man Golfing","Activity"],
//        ["🏌️‍♀️","Woman Golfing","Activity"],
//        ["🏄","Person Surfing","Activity"],
//        ["🏄‍♂️","Man Surfing","Activity"],
//        ["🏄‍♀️","Woman Surfing","Activity"],
//        ["🚣","Person Rowing Boat","Activity"],
//        ["🚣‍♂️","Man Rowing Boat","Activity"],
//        ["🚣‍♀️","Woman Rowing Boat","Activity"],
//        ["🏊"," Person Swimming","Activity"],
//        ["🏊‍♂️","Man Swimming","Activity"],
//        ["🏊‍♀️","Woman Swimming","Activity"],
//        ["⛹️","Person Bouncing Ball","Activity"],
//        ["⛹️‍♂️","Man Bouncing Ball","Activity"],
//        ["⛹️‍♀️","Woman Bouncing Ball","Activity"],
//        ["🏋️","Person Lifting Weights","Activity"],
//        ["🏋️‍♂️","Man Lifting Weights","Activity"],
//        ["🏋️‍♀️","Woman Lifting Weights","Activity"],
//        ["🚴","Person Biking","Activity"],
//        ["🚴‍♂️","Man Biking","Activity"],
//        ["🚴‍♀️","Woman Biking","Activity"],
//        ["🚵","Person Mountain Biking","Activity"],
//        ["🚵‍♂️","Man Mountain Biking","Activity"],
//        ["🚵‍♀️","Woman Mountain Biking","Activity"],
//        ["🤸","Person Cartwheeling","Activity"],
//        ["🤸‍♂️","Man Cartwheeling","Activity"],
//        ["🤸‍♀️"," Woman Cartwheeling","Activity"],
//        ["🤼","People Wrestling","Activity"],
//        ["🤼‍♂️","Men Wrestling","Activity"],
//        ["🤼‍♀️","Women Wrestling","Activity"],
//        ["🤽","Person Playing Water Polo","Activity"],
//        ["🤽‍♂️","Man Playing Water Polo","Activity"],
//        ["🤽‍♀️","Woman Playing Water Polo","Activity"],
//        ["🤾","Person Playing Handball","Activity"],
//        ["🤾‍♂️","Man Playing Handball","Activity"],
//        ["🤾‍♀️","Woman Playing Handball","Activity"],
//        ["🤹","Person Juggling","Activity"],
//        ["🤹‍♂️","Man Juggling","Activity"],
//        ["🤹‍♀️","Woman Juggling","Activity"],
//        ["🧘","Person in Lotus Position","Activity"],
//        ["🧘‍♂️","Man in Lotus Position","Activity"],
//        ["🧘‍♀️","Woman in Lotus Position","Activity"],
//        ["🎪","Circus Tent","Activity"],
//        ["🛹","Skateboard","Activity"],
//        ["🛼","Roller Skate","Activity"],
//        ["🛶","Canoe","Activity"],
//        ["🎗","Reminder Ribbon","Activity"],
//        ["🎟","Admission Tickets","Activity"],
//        ["🎫","Ticket","Activity"],
//        ["🎖","Military Medal","Activity"],
//        ["🏆","Trophy","Activity"],
//        ["🏅","Sports Medal","Activity"],
//        ["🥇","1st Place Medal","Activity"],
//        ["🥈","2nd Place Medal","Activity"],
//        ["🥉","3rd Place Medal","Activity"],
//        ["⚽","Soccer Ball","Activity"],
//        ["⚾","Baseball","Activity"],
//        ["🥎","Softball","Activity"],
//        ["🏀","Basketball","Activity"],
//        ["🏐","Volleyball","Activity"],
//        ["🏈","American Football","Activity"],
//        ["🏉","Rugby Football","Activity"],
//        ["🎾","Tennis","Activity"],
//        ["🥏","Flying Disc","Activity"],
//        ["🎳","Bowling","Activity"],
//        ["🏏","Cricket Game","Activity"],
//        ["🏑","Field Hockey","Activity"],
//        ["🏒","Ice Hockey","Activity"],
//        ["🥍","Lacrosse","Activity"],
//        ["🏓","Ping Pong","Activity"],
//        ["🏸","Badminton","Activity"],
//        ["🥊","Boxing Glove","Activity"],
//        ["🥋","Martial Arts Uniform","Activity"],
//        ["🥅","Goal Net","Activity"],
//        ["⛳","Flag in Hole","Activity"],
//        ["⛸️","Ice Skate","Activity"],
//        ["🎣","Fishing Pole","Activity"],
//        ["🎽","Running Shirt","Activity"],
//        ["🎿","Skis","Activity"],
//        ["🛷","Sled","Activity"],
//        ["🥌","Curling Stone","Activity"],
//        ["🎯","Direct Hit","Activity"],
//        ["🎱","Pool 8 Ball","Activity"],
//        ["🎮","Video Game","Activity"],
//        ["🎰","Slot Machine","Activity"],
//        ["🎲","Game Die","Activity"],
//        ["🧩","Puzzle Piece","Activity"],
//        ["♟️","Chess Pawn","Activity"],
//        ["🎭","Performing Arts","Activity"],
//        ["🎨","Artist Palette","Activity"],
//        ["🧵","Thread","Activity"],
//        ["🧶","Yarn","Activity"],
//        ["🎼","Musical Score","Activity"],
//        ["🎤","Microphone","Activity"],
//        ["🎧","Headphone","Activity"],
//        ["🎷","Saxophone","Activity"],
//        ["🪗","Accordion","Activity"],
//        ["🎸","Guitar","Activity"],
//        ["🎹","Musical Keyboard","Activity"],
//        ["🎺","Trumpet","Activity"],
//        ["🎻","Violin","Activity"],
//        ["🥁","Drum","Activity"],
//        ["🪘","Long Drum","Activity"],
//        ["🎬","Clapper Board","Activity"],
//        ["🏹","Bow and Arrow","Activity"],
//        ["👋","Waving Hand","Hand Gestures"],
//        ["🤚","Raised Back of Hand","Hand Gestures"],
//        ["🖐️","Hand with Fingers Splayed","Hand Gestures"],
//        ["✋","Raised Hand","Hand Gestures"],
//        ["🖖","Vulcan Salute, Live long prosper","Hand Gestures"],
//        ["🫱","Rightwards Hand","Hand Gestures"],
//        ["🫲","Leftwards Hand","Hand Gestures"],
//        ["🫳","Palm Down Hand","Hand Gestures"],
//        ["🫴","Palm Up Hand","Hand Gestures"],
//        ["👌","OK Hand","Hand Gestures"],
//        ["🤌","Pinched Fingers","Hand Gestures"],
//        ["🤏","Pinching Hand","Hand Gestures"],
//        ["✌️","Victory Hand","Hand Gestures"],
//        ["🤞","Crossed Fingers","Hand Gestures"],
//        ["🫰","Hand with Index Finger and Thumb Crossed","Hand Gestures"],
//        ["🤟","Love-You Gesture","Hand Gestures"],
//        ["🤘","Sign of the Horns","Hand Gestures"],
//        ["🤙","Call Me Hand","Hand Gestures"],
//        ["👈","Backhand Index Pointing Left","Hand Gestures"],
//        ["👉","Backhand Index Pointing Right","Hand Gestures"],
//        ["👆","Backhand Index Pointing Up","Hand Gestures"],
//        ["🖕","Middle Finger","Hand Gestures"],
//        ["👇","Backhand Index Pointing Down","Hand Gestures"],
//        ["☝️","Index Pointing Up","Hand Gestures"],
//        ["🫵","Index Pointing at the Viewer","Hand Gestures"],
//        ["👍","Thumbs Up","Hand Gestures"],
//        ["👎","Thumbs Down","Hand Gestures"],
//        ["✊","Raised Fist","Hand Gestures"],
//        ["👊","Oncoming Fist","Hand Gestures"],
//        ["🤛","Left-Facing Fist, Punch","Hand Gestures"],
//        ["🤜","Right-Facing Fist, Punch","Hand Gestures"],
//        ["👏","Clapping Hands","Hand Gestures"],
//        ["🙌","Raising Hands","Hand Gestures"],
//        ["🫶","Heart Hands","Hand Gestures"],
//        ["👐","Open Hands","Hand Gestures"],
//        ["🤲","Palms Up Together","Hand Gestures"],
//        ["🤝","Handshake","Hand Gestures"],
//        ["🙏","Folded Hands, Thank you, Praying","Hand Gestures"],
//        ["✍️","Writing Hand","Clothing & Accessories"],
//        ["💅","Nail Polish","Clothing & Accessories"],
//        ["🤳","Selfie","Clothing & Accessories"],
//        ["💪","Flexed Biceps","Clothing & Accessories"],
//        ["🦾","Mechanical Arm","Clothing & Accessories"],
//        ["🦿","Mechanical Leg","Clothing & Accessories"],
//        ["🦵","Leg","Clothing & Accessories"],
//        ["🦶","Foot","Clothing & Accessories"],
//        ["👂","Ear","Clothing & Accessories"],
//        ["🦻","Ear with Hearing Aid","Clothing & Accessories"],
//        ["👃","Nose","Clothing & Accessories"],
//        ["🧠","Brain","Clothing & Accessories"],
//        ["🫀","Anatomical Heart","Clothing & Accessories"],
//        ["🫁","Lungs","Clothing & Accessories"],
//        ["🦷","Tooth","Clothing & Accessories"],
//        ["🦴","Bone","Clothing & Accessories"],
//        ["👀","Eyes","Clothing & Accessories"],
//        ["👁️","Eye","Clothing & Accessories"],
//        ["👅","Tongue","Clothing & Accessories"],
//        ["👄","Mouth","Clothing & Accessories"],
//        ["🫦","Biting Lip","Clothing & Accessories"],
//        ["👣","Footprints","Clothing & Accessories"],
//        ["🧳","Luggage","Clothing & Accessories"],
//        ["🌂","Closed Umbrella","Clothing & Accessories"],
//        ["☂️","Umbrella","Clothing & Accessories"],
//        ["🎃","Jack-O-Lantern, Pumpkin","Clothing & Accessories"],
//        ["🧵","Thread","Clothing & Accessories"],
//        ["🧶","Yarn","Clothing & Accessories"],
//        ["👓","Glasses","Clothing & Accessories"],
//        ["🕶️","Sunglasses","Clothing & Accessories"],
//        ["🥽","Goggles","Clothing & Accessories"],
//        ["🥼","Lab Coat","Clothing & Accessories"],
//        ["🦺","Safety Vest","Clothing & Accessories"],
//        ["👔","Necktie","Clothing & Accessories"],
//        ["👕","T-Shirt","Clothing & Accessories"],
//        ["👖","Jeans","Clothing & Accessories"],
//        ["🧣","Scarf","Clothing & Accessories"],
//        ["🧤","Gloves","Clothing & Accessories"],
//        ["🧥","Coat","Clothing & Accessories"],
//        ["🧦","Socks","Clothing & Accessories"],
//        ["👗","Dress","Clothing & Accessories"],
//        ["👘","Kimono","Clothing & Accessories"],
//        ["🥻","Sari","Clothing & Accessories"],
//        ["🩱","One-Piece Swimsuit","Clothing & Accessories"],
//        ["🩲","Briefs","Clothing & Accessories"],
//        ["🩳","Shorts","Clothing & Accessories"],
//        ["👙","Bikini","Clothing & Accessories"],
//        ["👚","Woman’s Clothes","Clothing & Accessories"],
//        ["👛","Purse","Clothing & Accessories"],
//        ["👜","Handbag","Clothing & Accessories"],
//        ["👝","Clutch Bag","Clothing & Accessories"],
//        ["🎒","Backpack","Clothing & Accessories"],
//        ["🩴","Thong Sandal","Clothing & Accessories"],
//        ["👞","Man’s Shoe","Clothing & Accessories"],
//        ["👟","Running Shoe","Clothing & Accessories"],
//        ["🥾","Hiking Boot","Clothing & Accessories"],
//        ["🥿","Flat Shoe","Clothing & Accessories"],
//        ["👠","High-Heeled Shoe","Clothing & Accessories"],
//        ["👡","Woman’s Sandal","Clothing & Accessories"],
//        ["🩰","Ballet Shoes","Clothing & Accessories"],
//        ["👢","Woman’s Boot","Clothing & Accessories"],
//        ["👑","Crown","Clothing & Accessories"],
//        ["👒","Woman’s Hat","Clothing & Accessories"],
//        ["🎩","Top Hat","Clothing & Accessories"],
//        ["🎓","Graduation Cap","Clothing & Accessories"],
//        ["🧢","Billed Cap","Clothing & Accessories"],
//        ["🪖","Military Helmet","Clothing & Accessories"],
//        ["⛑️","Rescue Worker’s Helmet","Clothing & Accessories"],
//        ["💄","Lipstick","Clothing & Accessories"],
//        ["💍","Ring","Clothing & Accessories"],
//        ["💼","Briefcase","Clothing & Accessories"],
//        ["🩸","Drop of Blood","Clothing & Accessories"],
//
//        ["🐵","Monkey Face","Animals"],
//        ["🐒","Monkey","Animals"],
//        ["🦍","Gorilla","Animals"],
//        ["🦧","Orangutan","Animals"],
//        ["🐶","Dog Face","Animals"],
//        ["🐕","Dog","Animals"],
//        ["🦮","Guide Dog","Animals"],
//        ["🐕‍🦺","Service Dog","Animals"],
//        ["🐩","Poodle","Animals"],
//        ["🐺","Wolf","Animals"],
//        ["🦊","Fox","Animals"],
//        ["🦝","Raccoon","Animals"],
//        ["🐱","Cat Face","Animals"],
//        ["🐈","Cat","Animals"],
//        ["🐈‍⬛","Black Cat","Animals"],
//        ["🦁","Lion","Animals"],
//        ["🐯","Tiger Face","Animals"],
//        ["🐅","Tiger","Animals"],
//        ["🐆","Leopard","Animals"],
//        ["🐴","Horse Face","Animals"],
//        ["🐎","Horse","Animals"],
//        ["🦄","Unicorn","Animals"],
//        ["🦓","Zebra","Animals"],
//        ["🦌","Deer","Animals"],
//        ["🦬","Bison","Animals"],
//        ["🐮","Cow Face","Animals"],
//        ["🐂","Ox","Animals"],
//        ["🐃","Water Buffalo","Animals"],
//        ["🐄","Cow","Animals"],
//        ["🐷","Pig Face","Animals"],
//        ["🐖","Pig","Animals"],
//        ["🐗","Boar","Animals"],
//        ["🐽","Pig Nose","Animals"],
//        ["🐏","Ram","Animals"],
//        ["🐑","Ewe","Animals"],
//        ["🐐","Goat","Animals"],
//        ["🐪","Camel","Animals"],
//        ["🐫","Two-Hump Camel","Animals"],
//        ["🦙","Llama","Animals"],
//        ["🦒","Giraffe","Animals"],
//        ["🐘","Elephant","Animals"],
//        ["🦣","Mammoth","Animals"],
//        ["🦏","Rhinoceros","Animals"],
//        ["🦛","Hippopotamus","Animals"],
//        ["🐭","Mouse Face","Animals"],
//        ["🐁","Mouse","Animals"],
//        ["🐀","Rat","Animals"],
//        ["🐹","Hamster","Animals"],
//        ["🐰","Rabbit Face","Animals"],
//        ["🐇","Rabbit","Animals"],
//        ["🐿","Chipmunk","Animals"],
//        ["🦫","Beaver","Animals"],
//        ["🦔","Hedgehog","Animals"],
//        ["🦇","Bat","Animals"],
//        ["🐻","Bear","Animals"],
//        ["🐻‍❄️","Polar Bear","Animals"],
//        ["🐨","Koala","Animals"],
//        ["🐼","Panda","Animals"],
//        ["🦥","Sloth","Animals"],
//        ["🦦","Otter","Animals"],
//        ["🦨","Skunk","Animals"],
//        ["🦘","Kangaroo","Animals"],
//        ["🦡","Badger","Animals"],
//        ["🐾","Paw Prints","Animals"],
//        ["🦃","Turkey","Animals"],
//        ["🐔","Chicken","Animals"],
//        ["🐓","Rooster","Animals"],
//        ["🐣","Hatching Chick","Animals"],
//        ["🐤","Baby Chick","Animals"],
//        ["🐥","Front-Facing Baby Chick","Animals"],
//        ["🐦","Bird","Animals"],
//        ["🐧","Penguin","Animals"],
//        ["🕊","Dove","Animals"],
//        ["🦅","Eagle","Animals"],
//        ["🦆","Duck","Animals"],
//        ["🦢","Swan","Animals"],
//        ["🦉","Owl","Animals"],
//        ["🦤","Dodo","Animals"],
//        ["🪶","Feather","Animals"],
//        ["🦩","Flamingo","Animals"],
//        ["🦚","Peacock","Animals"],
//        ["🦜","Parrot","Animals"],
//        ["🐸","Frog","Animals"],
//        ["🐊","Crocodile","Animals"],
//        ["🐢","Turtle","Animals"],
//        ["🦎","Lizard","Animals"],
//        ["🐍","Snake","Animals"],
//        ["🐲","Dragon Face","Animals"],
//        ["🐉","Dragon","Animals"],
//        ["🦕","Sauropod","Animals"],
//        ["🦖","T-Rex","Animals"],
//        ["🐳","Spouting Whale","Animals"],
//        ["🐋","Whale","Animals"],
//        ["🐬","Dolphin","Animals"],
//        ["🦭","Seal","Animals"],
//        ["🐟","Fish","Animals"],
//        ["🐠","Tropical Fish","Animals"],
//        ["🐡","Blowfish","Animals"],
//        ["🦈","Shark","Animals"],
//        ["🐙","Octopus","Animals"],
//        ["🐚","Spiral Shell","Animals"],
//        ["🐌","Snail","Animals"],
//        ["🦋","Butterfly","Animals"],
//        ["🐛","Bug","Animals"],
//        ["🐜","Ant","Animals"],
//        ["🐝","Honeybee","Animals"],
//        ["🪲","Beetle","Animals"],
//        ["🐞","Lady Beetle","Animals"],
//        ["🦗","Cricket","Animals"],
//        ["🪳","Cockroach","Animals"],
//        ["🕷","Spider","Animals"],
//        ["🕸","Spider Web","Animals"],
//        ["🦂","Scorpion","Animals"],
//        ["🦟","Mosquito","Animals"],
//        ["🪰","Fly","Animals"],
//        ["🪱","Worm","Animals"],
//        ["🦠","Microbe","Animals"],
//        ["💐","Bouquet","Nature"],
//        ["🌸","Cherry Blossom","Nature"],
//        ["💮","White Flower","Nature"],
//        ["🏵","Rosette","Nature"],
//        ["🌹","Rose","Nature"],
//        ["🥀","Wilted Flower","Nature"],
//        ["🌺","Hibiscus","Nature"],
//        ["🌻","Sunflower","Nature"],
//        ["🌼","Blossom","Nature"],
//        ["🌷","Tulip","Nature"],
//        ["🌱","Seedling","Nature"],
//        ["🪴","Potted Plant","Nature"],
//        ["🌲","Evergreen Tree","Nature"],
//        ["🌳","Deciduous Tree","Nature"],
//        ["🌴","Palm Tree","Nature"],
//        ["🌵","Cactus","Nature"],
//        ["🌾","Sheaf of Rice","Nature"],
//        ["🌿","Herb","Nature"],
//        ["☘️","Shamrock","Nature"],
//        ["🍀","Four Leaf Clover","Nature"],
//        ["🍁","Maple Leaf","Nature"],
//        ["🍂","Fallen Leaf","Nature"],
//        ["🍃","Leaf Fluttering in Wind","Nature"],
//        ["🍄","Mushroom","Nature"],
//        ["🌰","Chestnut","Nature"],
//        ["🦀","Crab","Nature"],
//        ["🦞","Lobster","Nature"],
//        ["🦐","Shrimp","Nature"],
//        ["🦑","Squid","Nature"],
//        ["🌍","Globe Showing Europe-Africa","Nature"],
//        ["🌎","Globe Showing Americas","Nature"],
//        ["🌏","Globe Showing Asia-Australia","Nature"],
//        ["🌐","Globe with Meridians","Nature"],
//        ["🪨","Rock","Nature"],
//        ["🎄","Christmas Tree","Nature"],
//        ["✨","Sparkles","Nature"],
//        ["🎋","Tanabata Tree","Nature"],
//        ["🎍","Pine Decoration","Nature"],
//        ["🌑","New Moon, Sky","Sky & Weather"],
//        ["🌒","Waxing Crescent Moon, Sky","Sky & Weather"],
//        ["🌓","First Quarter Moon, Sky","Sky & Weather"],
//        ["🌔","Waxing Gibbous Moon, Sky","Sky & Weather"],
//        ["🌕","Full Moon, Sky","Sky & Weather"],
//        ["🌖","Waning Gibbous Moon, Sky","Sky & Weather"],
//        ["🌗","Last Quarter Moon, Sky","Sky & Weather"],
//        ["🌘","Waning Crescent Moon, Sky","Sky & Weather"],
//        ["🌙","Crescent Moon, Sky","Sky & Weather"],
//        ["🌚","New Moon Face, Sky","Sky & Weather"],
//        ["🌛","First Quarter Moon Face, Sky","Sky & Weather"],
//        ["🌜","Last Quarter Moon Face, Sky","Sky & Weather"],
//        ["☀️","Sun, Sky","Sky & Weather"],
//        ["🌝","Full Moon Face, Sky","Sky & Weather"],
//        ["🌞","Sun with Face, Sky","Sky & Weather"],
//        ["⭐","Star, Sky","Sky & Weather"],
//        ["🌟","Glowing Star, Sky","Sky & Weather"],
//        ["🌠","Shooting Star, Sky","Sky & Weather"],
//        ["☁️","Cloud, Weather","Sky & Weather"],
//        ["⛅","Sun Behind Cloud, Weather","Sky & Weather"],
//        ["⛈️","Cloud with Lightning and Rain, Weather","Sky & Weather"],
//        ["🌤","Sun Behind Small Cloud, Weather","Sky & Weather"],
//        ["🌥","Sun Behind Large Cloud, Weather","Sky & Weather"],
//        ["🌦","Sun Behind Rain Cloud, Weather","Sky & Weather"],
//        ["🌧","Cloud with Rain, Weather","Sky & Weather"],
//        ["🌨","Cloud with Snow, Weather","Sky & Weather"],
//        ["🌩","Cloud with Lightning, Weather","Sky & Weather"],
//        ["🌪","Tornado, Weather","Sky & Weather"],
//        ["🌫","Fog, Weather","Sky & Weather"],
//        ["🌬","Wind Face, Weather","Sky & Weather"],
//        ["🌈","Rainbow, Weather","Sky & Weather"],
//        ["☂️","Umbrella, Weather","Sky & Weather"],
//        ["☔","Umbrella with Rain Drops, Weather","Sky & Weather"],
//        ["⚡","High Voltage, Lightning, Weather","Sky & Weather"],
//        ["❄️","Snowflake, Weather","Sky & Weather"],
//        ["☃️","Snowman, Weather","Sky & Weather"],
//        ["⛄","Snowman Without Snow, Weather","Sky & Weather"],
//        ["☄️","Comet, Weather","Sky & Weather"],
//        ["🔥","Fire, Weather","Sky & Weather"],
//        ["💧","Droplet, Weather","Sky & Weather"],
//        ["🌊","Water Wave, Weather","Sky & Weather"],
//        ["🍇","Grapes, Fruit","Food & Drink"],
//        ["🍈","Melon, Fruit","Food & Drink"],
//        ["🍉","Watermelon, Fruit","Food & Drink"],
//        ["🍊","Tangerine, Fruit","Food & Drink"],
//        ["🍋","Lemon, Fruit","Food & Drink"],
//        ["🍌","Banana, Fruit","Food & Drink"],
//        ["🍍","Pineapple, Fruit","Food & Drink"],
//        ["🥭","Mango, Fruit","Food & Drink"],
//        ["🍎","Red Apple, Fruit","Food & Drink"],
//        ["🍏","Green Apple, Fruit","Food & Drink"],
//        ["🍐","Pear, Fruit","Food & Drink"],
//        ["🍑","Peach, Fruit","Food & Drink"],
//        ["🍒","Cherries, Fruit","Food & Drink"],
//        ["🍓","Strawberry, Fruit","Food & Drink"],
//        ["🫐","Blueberries, Fruit","Food & Drink"],
//        ["🥝","Kiwi Fruit","Food & Drink"],
//        ["🍅","Tomato, Fruit","Food & Drink"],
//        ["🫒","Olive, Fruit","Food & Drink"],
//        ["🥥","Coconut, Fruit","Food & Drink"],
//        ["🥑","Avocado, Vegetable","Food & Drink"],
//        ["🍆","Eggplant, Vegetable","Food & Drink"],
//        ["🥔","Potato, Vegetable","Food & Drink"],
//        ["🥕","Carrot, Vegetable","Food & Drink"],
//        ["🌽","Ear of Corn, Vegetable","Food & Drink"],
//        ["🌶","Hot Pepper, Vegetable","Food & Drink"],
//        ["🫑","Bell Pepper, Vegetable","Food & Drink"],
//        ["🥒","Cucumber, Vegetable","Food & Drink"],
//        ["🥬","Leafy Green, Vegetable","Food & Drink"],
//        ["🥦","Broccoli, Vegetable","Food & Drink"],
//        ["🧄","Garlic, Vegetable","Food & Drink"],
//        ["🧅","Onion, Vegetable","Food & Drink"],
//        ["🍄","Mushroom","Food & Drink"],
//        ["🥜","Peanuts","Food & Drink"],
//        ["🌰","Chestnut","Food & Drink"],
//        ["🍞","Bread","Food & Drink"],
//        ["🥐","Croissant","Food & Drink"],
//        ["🥖","Baguette Bread","Food & Drink"],
//        ["🫓","Flatbread","Food & Drink"],
//        ["🥨","Pretzel","Food & Drink"],
//        ["🥯","Bagel","Food & Drink"],
//        ["🥞","Pancakes","Food & Drink"],
//        ["🧇","Waffle","Food & Drink"],
//        ["🧀","Cheese Wedge","Food & Drink"],
//        ["🍖","Meat on Bone","Food & Drink"],
//        ["🍗","Poultry Leg","Food & Drink"],
//        ["🥩","Cut of Meat","Food & Drink"],
//        ["🥓","Bacon","Food & Drink"],
//        ["🍔","Hamburger","Food & Drink"],
//        ["🍟","French Fries","Food & Drink"],
//        ["🍕","Pizza","Food & Drink"],
//        ["🌭","Hot Dog","Food & Drink"],
//        ["🥪","Sandwich","Food & Drink"],
//        ["🌮","Taco","Food & Drink"],
//        ["🌯","Burrito","Food & Drink"],
//        ["🫔","Tamale","Food & Drink"],
//        ["🥙","Stuffed Flatbread","Food & Drink"],
//        ["🧆","Falafel","Food & Drink"],
//        ["🥚","Egg","Food & Drink"],
//        ["🍳","Cooking","Food & Drink"],
//        ["🥘","Shallow Pan of Food","Food & Drink"],
//        ["🍲","Pot of Food","Food & Drink"],
//        ["🫕","Fondue","Food & Drink"],
//        ["🥣","Bowl with Spoon","Food & Drink"],
//        ["🥗","Green Salad","Food & Drink"],
//        ["🍿","Popcorn","Food & Drink"],
//        ["🧈","Butter","Food & Drink"],
//        ["🧂","Salt","Food & Drink"],
//        ["🥫","Canned Food","Food & Drink"],
//        ["🍱","Bento Box, Asian","Food & Drink"],
//        ["🍘","Rice Cracker, Asian","Food & Drink"],
//        ["🍙","Rice Ball, Asian","Food & Drink"],
//        ["🍚","Cooked Rice, Asian","Food & Drink"],
//        ["🍛","Curry Rice, Asian","Food & Drink"],
//        ["🍜","Steaming Bowl, Asian","Food & Drink"],
//        ["🍝","Spaghetti","Food & Drink"],
//        ["🍠","Roasted Sweet Potato","Food & Drink"],
//        ["🍢","Oden","Food & Drink"],
//        ["🍣","Sushi","Food & Drink"],
//        ["🍤","Fried Shrimp","Food & Drink"],
//        ["🍥","Fish Cake with Swirl","Food & Drink"],
//        ["🥮","Moon Cake","Food & Drink"],
//        ["🍡","Dango","Food & Drink"],
//        ["🥟","Dumpling","Food & Drink"],
//        ["🥠","Fortune Cookie","Food & Drink"],
//        ["🥡","Takeout Box","Food & Drink"],
//        ["🦪","Oyster","Food & Drink"],
//        ["🍦","Soft Ice Cream, Sweet, Dessert","Food & Drink"],
//        ["🍧","Shaved Ice, Sweet, Dessert","Food & Drink"],
//        ["🍨","Ice Cream, Sweet, Dessert","Food & Drink"],
//        ["🍩","Doughnut, Sweet, Dessert","Food & Drink"],
//        ["🍪","Cookie, Sweet, Dessert","Food & Drink"],
//        ["🎂","Birthday Cake, Sweet, Dessert","Food & Drink"],
//        ["🍰","Shortcake, Sweet, Dessert","Food & Drink"],
//        ["🧁","Cupcake, Sweet, Dessert","Food & Drink"],
//        ["🥧","Pie, Sweet, Dessert","Food & Drink"],
//        ["🍫","Chocolate Bar, Sweet, Dessert","Food & Drink"],
//        ["🍬","Candy, Sweet, Dessert","Food & Drink"],
//        ["🍭","Lollipop, Sweet, Dessert","Food & Drink"],
//        ["🍮","Custard, Sweet, Dessert","Food & Drink"],
//        ["🍯","Honey, Bee, Bear, Sweet","Food & Drink"],
//        ["🍼","Baby Bottle, Drink","Food & Drink"],
//        ["🥛","Glass of Milk, Drink","Food & Drink"],
//        ["☕","Hot Beverage, Drink","Food & Drink"],
//        ["🫖","Teapot, Drink","Food & Drink"],
//        ["🍵","Teacup Without Handle, Drink","Food & Drink"],
//        ["🍶","Sake, Drink","Food & Drink"],
//        ["🍾","Bottle with Popping Cork, Drink","Food & Drink"],
//        ["🍷","Wine Glass, Drink","Food & Drink"],
//        ["🍸","Cocktail Glass, Drink","Food & Drink"],
//        ["🍹","Tropical Drink, Drink","Food & Drink"],
//        ["🍺","Beer Mug, Drink","Food & Drink"],
//        ["🍻","Clinking Beer Mugs, Drink","Food & Drink"],
//        ["🥂","Clinking Glasses, Drink","Food & Drink"],
//        ["🥃","Tumbler Glass, Drink","Food & Drink"],
//        ["🥤","Cup with Straw, Drink","Food & Drink"],
//        ["🧋","Bubble Tea, Drink","Food & Drink"],
//        ["🧃","Beverage Box, Drink","Food & Drink"],
//        ["🧉","Mate, Drink","Food & Drink"],
//        ["🧊","Ice, Drink","Food & Drink"],
//        ["🥢","Chopsticks, Dishware, Cutlery","Food & Drink"],
//        ["🍽","Fork and Knife with Plate, Dishware, Cutlery","Food & Drink"],
//        ["🍴","Fork and Knife, Dishware, Cutlery","Food & Drink"],
//        ["🥄","Spoon, Dishware, Cutlery","Food & Drink"],
//        ["🚣","Rowing Boat","Travel & Places"],
//        ["🗾","Map of Japan","Travel & Places"],
//        ["🏔","Snow-Capped Mountain","Travel & Places"],
//        ["⛰️","Mountain","Travel & Places"],
//        ["🌋","Volcano","Travel & Places"],
//        ["🗻","Mount Fuji","Travel & Places"],
//        ["🏕","Camping","Travel & Places"],
//        ["🏖","Beach with Umbrella","Travel & Places"],
//        ["🏜","Desert","Travel & Places"],
//        ["🏝","Desert Island","Travel & Places"],
//        ["🏞","National Park","Travel & Places"],
//        ["🏟","Stadium","Travel & Places"],
//        ["🏛","Classical Building","Travel & Places"],
//        ["🏗","Building Construction","Travel & Places"],
//        ["🛖","Hut","Travel & Places"],
//        ["🏘","Houses","Travel & Places"],
//        ["🏚","Derelict House","Travel & Places"],
//        ["🏠","House","Travel & Places"],
//        ["🏡","House with Garden","Travel & Places"],
//        ["🏢","Office Building","Travel & Places"],
//        ["🏣","Japanese Post Office","Travel & Places"],
//        ["🏤","Post Office","Travel & Places"],
//        ["🏥","Hospital","Travel & Places"],
//        ["🏦","Bank","Travel & Places"],
//        ["🏨","Hotel","Travel & Places"],
//        ["🏩","Love Hotel","Travel & Places"],
//        ["🏪","Convenience Store","Travel & Places"],
//        ["🏫","School","Travel & Places"],
//        ["🏬","Department Store","Travel & Places"],
//        ["🏭","Factory","Travel & Places"],
//        ["🏯","Japanese Castle","Travel & Places"],
//        ["🏰","Castle","Travel & Places"],
//        ["💒","Wedding","Travel & Places"],
//        ["🗼","Tokyo Tower","Travel & Places"],
//        ["🗽","Statue of Liberty","Travel & Places"],
//        ["⛪","Church","Travel & Places"],
//        ["🕌","Mosque","Travel & Places"],
//        ["🛕","Hindu Temple","Travel & Places"],
//        ["🕍","Synagogue","Travel & Places"],
//        ["⛩️","Shinto Shrine","Travel & Places"],
//        ["🕋","Kaaba","Travel & Places"],
//        ["⛲","Fountain","Travel & Places"],
//        ["⛺","Tent","Travel & Places"],
//        ["🌁","Foggy","Travel & Places"],
//        ["🌃","Night with Stars","Travel & Places"],
//        ["🏙","Cityscape","Travel & Places"],
//        ["🌄","Sunrise Over Mountains","Travel & Places"],
//        ["🌅","Sunrise","Travel & Places"],
//        ["🌆","Cityscape at Dusk","Travel & Places"],
//        ["🌇","Sunset","Travel & Places"],
//        ["🌉","Bridge at Night","Travel & Places"],
//        ["🎠","Carousel Horse","Travel & Places"],
//        ["🎡","Ferris Wheel","Travel & Places"],
//        ["🎢","Roller Coaster","Travel & Places"],
//        ["🚂","Locomotive","Travel & Places"],
//        ["🚃","Railway Car","Travel & Places"],
//        ["🚄","High-Speed Train","Travel & Places"],
//        ["🚅","Bullet Train","Travel & Places"],
//        ["🚆","Train","Travel & Places"],
//        ["🚇","Metro","Travel & Places"],
//        ["🚈","Light Rail","Travel & Places"],
//        ["🚉","Station","Travel & Places"],
//        ["🚊","Tram","Travel & Places"],
//        ["🚝","Monorail","Travel & Places"],
//        ["🚞","Mountain Railway","Travel & Places"],
//        ["🚋","Tram Car","Travel & Places"],
//        ["🚌","Bus","Travel & Places"],
//        ["🚍","Oncoming Bus","Travel & Places"],
//        ["🚎","Trolleybus","Travel & Places"],
//        ["🚐","Minibus","Travel & Places"],
//        ["🚑","Ambulance","Travel & Places"],
//        ["🚒","Fire Engine","Travel & Places"],
//        ["🚓","Police Car","Travel & Places"],
//        ["🚔","Oncoming Police Car","Travel & Places"],
//        ["🚕","Taxi","Travel & Places"],
//        ["🚖","Oncoming Taxi","Travel & Places"],
//        ["🚗","Automobile","Travel & Places"],
//        ["🚘","Oncoming Automobile","Travel & Places"],
//        ["🚙","Sport Utility Vehicle","Travel & Places"],
//        ["🛻","Pickup Truck","Travel & Places"],
//        ["🚚","Delivery Truck","Travel & Places"],
//        ["🚛","Articulated Lorry","Travel & Places"],
//        ["🚜","Tractor","Travel & Places"],
//        ["🏎","Racing Car","Travel & Places"],
//        ["🏍","Motorcycle","Travel & Places"],
//        ["🛵","Motor Scooter","Travel & Places"],
//        ["🛺","Auto Rickshaw","Travel & Places"],
//        ["🚲","Bicycle","Travel & Places"],
//        ["🛴","Kick Scooter","Travel & Places"],
//        ["🚏","Bus Stop","Travel & Places"],
//        ["🛣","Motorway","Travel & Places"],
//        ["🛤","Railway Track","Travel & Places"],
//        ["⛽","Fuel Pump","Travel & Places"],
//        ["🚨","Police Car Light","Travel & Places"],
//        ["🚥","Horizontal Traffic Light","Travel & Places"],
//        ["🚦","Vertical Traffic Light","Travel & Places"],
//        ["🚧","Construction","Travel & Places"],
//        ["⚓","Anchor","Travel & Places"],
//        ["⛵","Sailboat","Travel & Places"],
//        ["🚤","Speedboat","Travel & Places"],
//        ["🛳","Passenger Ship","Travel & Places"],
//        ["⛴️","Ferry","Travel & Places"],
//        ["🛥","Motor Boat","Travel & Places"],
//        ["🚢","Ship","Travel & Places"],
//        ["✈️","Airplane","Travel & Places"],
//        ["🛩","Small Airplane","Travel & Places"],
//        ["🛫","Airplane Departure","Travel & Places"],
//        ["🛬","Airplane Arrival","Travel & Places"],
//        ["🪂","Parachute","Travel & Places"],
//        ["💺","Seat","Travel & Places"],
//        ["🚁","Helicopter","Travel & Places"],
//        ["🚟","Suspension Railway","Travel & Places"],
//        ["🚠","Mountain Cableway","Travel & Places"],
//        ["🚡","Aerial Tramway","Travel & Places"],
//        ["🛰","Satellite","Travel & Places"],
//        ["🚀","Rocket","Travel & Places"],
//        ["🛸","Flying Saucer","Travel & Places"],
//        ["🪐","Ringed Planet","Travel & Places"],
//        ["🌠","Shooting Star","Travel & Places"],
//        ["🌌","Milky Way","Travel & Places"],
//        ["⛱️","Umbrella on Ground","Travel & Places"],
//        ["🎆","Fireworks","Travel & Places"],
//        ["🎇","Sparkler","Travel & Places"],
//        ["🎑","Moon Viewing Ceremony","Travel & Places"],
//        ["💴","Yen Banknote","Travel & Places"],
//        ["💵","Dollar Banknote","Travel & Places"],
//        ["💶","Euro Banknote","Travel & Places"],
//        ["💷","Pound Banknote","Travel & Places"],
//        ["🗿","Moai","Travel & Places"],
//        ["🛂","Passport Control","Travel & Places"],
//        ["🛃","Customs","Travel & Places"],
//        ["🛄","Baggage Claim","Travel & Places"],
//        ["🛅","Left Luggage","Travel & Places"],
//        ["💌","Love Letter","Objects"],
//        ["🕳","Hole","Objects"],
//        ["💣","Bomb","Objects"],
//        ["🛀","Person Taking Bath","Objects"],
//        ["🛌","Person in Bed","Objects"],
//        ["🔪","Kitchen Knife","Objects"],
//        ["🏺","Amphora","Objects"],
//        ["🗺","World Map","Objects"],
//        ["🧭","Compass","Objects"],
//        ["🧱","Brick","Objects"],
//        ["💈","Barber Pole","Objects"],
//        ["🦽","Manual Wheelchair","Objects"],
//        ["🦼","Motorized Wheelchair","Objects"],
//        ["🛢","Oil Drum","Objects"],
//        ["🛎","Bellhop Bell","Objects"],
//        ["🧳","Luggage","Objects"],
//        ["⌛","Hourglass Done","Objects"],
//        ["⏳","Hourglass Not Done","Objects"],
//        ["⌚","Watch","Objects"],
//        ["⏰","Alarm Clock","Objects"],
//        ["⏱️","Stopwatch","Objects"],
//        ["⏲️","Timer Clock","Objects"],
//        ["🕰","Mantelpiece Clock","Objects"],
//        ["🌡","Thermometer","Objects"],
//        ["⛱️","Umbrella on Ground","Objects"],
//        ["🧨","Firecracker","Objects"],
//        ["🎈","Balloon","Objects"],
//        ["🎉","Party Popper","Objects"],
//        ["🎊","Confetti Ball","Objects"],
//        ["🎎","Japanese Dolls","Objects"],
//        ["🎏","Carp Streamer","Objects"],
//        ["🎐","Wind Chime","Objects"],
//        ["🧧","Red Envelope","Objects"],
//        ["🎀","Ribbon","Objects"],
//        ["🎁","Wrapped Gift","Objects"],
//        ["🤿","Diving Mask","Objects"],
//        ["🪀","Yo-Yo","Objects"],
//        ["🪁","Kite","Objects"],
//        ["🔮","Crystal Ball","Objects"],
//        ["🪄","Magic Wand","Objects"],
//        ["🧿","Nazar Amulet","Objects"],
//        ["🕹","Joystick","Objects"],
//        ["🧸","Teddy Bear","Objects"],
//        ["🪅","Piñata","Objects"],
//        ["🪆","Nesting Dolls","Objects"],
//        ["🖼","Framed Picture","Objects"],
//        ["🧵","Thread","Objects"],
//        ["🪡","Sewing Needle","Objects"],
//        ["🧶","Yarn","Objects"],
//        ["🪢","Knot","Objects"],
//        ["🛍","Shopping Bags","Objects"],
//        ["📿","Prayer Beads","Objects"],
//        ["💎","Gem Stone","Objects"],
//        ["📯","Postal Horn","Objects"],
//        ["🎙","Studio Microphone","Objects"],
//        ["🎚","Level Slider","Objects"],
//        ["🎛","Control Knobs","Objects"],
//        ["📻","Radio","Objects"],
//        ["🪕","Banjo","Objects"],
//        ["📱","Mobile Phone","Objects"],
//        ["📲","Mobile Phone with Arrow","Objects"],
//        ["☎️","Telephone","Objects"],
//        ["📞","Telephone Receiver","Objects"],
//        ["📟","Pager","Objects"],
//        ["📠","Fax Machine","Objects"],
//        ["🔋","Battery","Objects"],
//        ["🔌","Electric Plug","Objects"],
//        ["💻","Laptop","Objects"],
//        ["🖥","Desktop Computer","Objects"],
//        ["🖨","Printer","Objects"],
//        ["⌨️","Keyboard","Objects"],
//        ["🖱","Computer Mouse","Objects"],
//        ["🖲","Trackball","Objects"],
//        ["💽","Computer Disk","Objects"],
//        ["💾","Floppy Disk","Objects"],
//        ["💿","Optical Disk","Objects"],
//        ["📀","DVD","Objects"],
//        ["🧮","Abacus","Objects"],
//        ["🎥","Movie Camera","Objects"],
//        ["🎞","Film Frames","Objects"],
//        ["📽","Film Projector","Objects"],
//        ["📺","Television","Objects"],
//        ["📷","Camera","Objects"],
//        ["📸","Camera with Flash","Objects"],
//        ["📹","Video Camera","Objects"],
//        ["📼","Videocassette","Objects"],
//        ["🔍","Magnifying Glass Tilted Left","Objects"],
//        ["🔎","Magnifying Glass Tilted Right","Objects"],
//        ["🕯","Candle","Objects"],
//        ["💡","Light Bulb","Objects"],
//        ["🔦","Flashlight","Objects"],
//        ["🏮","Red Paper Lantern","Objects"],
//        ["🪔","Diya Lamp","Objects"],
//        ["📔","Notebook with Decorative Cover","Objects"],
//        ["📕","Closed Book","Objects"],
//        ["📖","Open Book","Objects"],
//        ["📗","Green Book","Objects"],
//        ["📘","Blue Book","Objects"],
//        ["📙","Orange Book","Objects"],
//        ["📚","Books","Objects"],
//        ["📓","Notebook","Objects"],
//        ["📒","Ledger","Objects"],
//        ["📃","Page with Curl","Objects"],
//        ["📜","Scroll","Objects"],
//        ["📄","Page Facing Up","Objects"],
//        ["📰","Newspaper","Objects"],
//        ["🗞","Rolled-Up Newspaper","Objects"],
//        ["📑","Bookmark Tabs","Objects"],
//        ["🔖","Bookmark","Objects"],
//        ["🏷","Label","Objects"],
//        ["💰","Money Bag","Objects"],
//        ["🪙","Coin","Objects"],
//        ["💴","Yen Banknote","Objects"],
//        ["💵","Dollar Banknote","Objects"],
//        ["💶","Euro Banknote","Objects"],
//        ["💷","Pound Banknote","Objects"],
//        ["💸","Money with Wings","Objects"],
//        ["💳","Credit Card","Objects"],
//        ["🧾","Receipt","Objects"],
//        ["✉️","Envelope","Objects"],
//        ["📧","E-Mail","Objects"],
//        ["📨","Incoming Envelope","Objects"],
//        ["📩","Envelope with Arrow","Objects"],
//        ["📤","Outbox Tray","Objects"],
//        ["📥","Inbox Tray","Objects"],
//        ["📦","Package","Objects"],
//        ["📫","Closed Mailbox with Raised Flag","Objects"],
//        ["📪","Closed Mailbox with Lowered Flag","Objects"],
//        ["📬","Open Mailbox with Raised Flag","Objects"],
//        ["📭","Open Mailbox with Lowered Flag","Objects"],
//        ["📮","Postbox","Objects"],
//        ["🗳","Ballot Box with Ballot","Objects"],
//        ["✏️","Pencil","Objects"],
//        ["✒️","Black Nib","Objects"],
//        ["🖋","Fountain Pen","Objects"],
//        ["🖊","Pen","Objects"],
//        ["🖌","Paintbrush","Objects"],
//        ["🖍","Crayon","Objects"],
//        ["📝","Memo","Objects"],
//        ["📁","File Folder","Objects"],
//        ["📂","Open File Folder","Objects"],
//        ["🗂","Card Index Dividers","Objects"],
//        ["📅","Calendar","Objects"],
//        ["📆","Tear-Off Calendar","Objects"],
//        ["🗒","Spiral Notepad","Objects"],
//        ["🗓","Spiral Calendar","Objects"],
//        ["📇","Card Index","Objects"],
//        ["📈","Chart Increasing","Objects"],
//        ["📉","Chart Decreasing","Objects"],
//        ["📊","Bar Chart","Objects"],
//        ["📋","Clipboard","Objects"],
//        ["📌","Pushpin","Objects"],
//        ["📍","Round Pushpin","Objects"],
//        ["📎","Paperclip","Objects"],
//        ["🖇","Linked Paperclips","Objects"],
//        ["📏","Straight Ruler","Objects"],
//        ["📐","Triangular Ruler","Objects"],
//        ["✂️","Scissors","Objects"],
//        ["🗃","Card File Box","Objects"],
//        ["🗄","File Cabinet","Objects"],
//        ["🗑","Wastebasket","Objects"],
//        ["🔒","Locked","Objects"],
//        ["🔓","Unlocked","Objects"],
//        ["🔏","Locked with Pen","Objects"],
//        ["🔐","Locked with Key","Objects"],
//        ["🔑","Key","Objects"],
//        ["🗝","Old Key","Objects"],
//        ["🔨","Hammer","Objects"],
//        ["🪓","Axe","Objects"],
//        ["⛏️","Pick","Objects"],
//        ["⚒️","Hammer and Pick","Objects"],
//        ["🛠","Hammer and Wrench","Objects"],
//        ["🗡","Dagger","Objects"],
//        ["⚔️","Crossed Swords","Objects"],
//        ["🔫","Pistol","Objects"],
//        ["🪃","Boomerang","Objects"],
//        ["🛡","Shield","Objects"],
//        ["🪚","Carpentry Saw","Objects"],
//        ["🔧","Wrench","Objects"],
//        ["🪛","Screwdriver","Objects"],
//        ["🔩","Nut and Bolt","Objects"],
//        ["⚙️","Gear","Objects"],
//        ["🗜","Clamp","Objects"],
//        ["⚖️","Balance Scale","Objects"],
//        ["🦯","White Cane","Objects"],
//        ["🔗","Link","Objects"],
//        ["⛓️","Chains","Objects"],
//        ["🪝","Hook","Objects"],
//        ["🧰","Toolbox","Objects"],
//        ["🧲","Magnet","Objects"],
//        ["🪜","Ladder","Objects"],
//        ["⚗️","Alembic","Objects"],
//        ["🧪","Test Tube","Objects"],
//        ["🧫","Petri Dish","Objects"],
//        ["🧬","DNA","Objects"],
//        ["🔬","Microscope","Objects"],
//        ["🔭","Telescope","Objects"],
//        ["📡","Satellite Antenna","Objects"],
//        ["💉","Syringe","Objects"],
//        ["🩸","Drop of Blood","Objects"],
//        ["💊","Pill","Objects"],
//        ["🩹","Adhesive Bandage","Objects"],
//        ["🩺","Stethoscope","Objects"],
//        ["🚪","Door","Objects"],
//        ["🪞","Mirror","Objects"],
//        ["🪟","Window","Objects"],
//        ["🛏","Bed","Objects"],
//        ["🛋","Couch and Lamp","Objects"],
//        ["🪑","Chair","Objects"],
//        ["🚽","Toilet","Objects"],
//        ["🪠","Plunger","Objects"],
//        ["🚿","Shower","Objects"],
//        ["🛁","Bathtub","Objects"],
//        ["🪤","Mouse Trap","Objects"],
//        ["🪒","Razor","Objects"],
//        ["🧴","Lotion Bottle","Objects"],
//        ["🧷","Safety Pin","Objects"],
//        ["🧹","Broom","Objects"],
//        ["🧺","Basket","Objects"],
//        ["🧻","Roll of Paper","Objects"],
//        ["🪣","Bucket","Objects"],
//        ["🧼","Soap","Objects"],
//        ["🪥","Toothbrush","Objects"],
//        ["🧽","Sponge","Objects"],
//        ["🧯","Fire Extinguisher","Objects"],
//        ["🛒","Shopping Cart","Objects"],
//        ["🚬","Cigarette","Objects"],
//        ["⚰️","Coffin","Objects"],
//        ["🪦","Headstone","Objects"],
//        ["⚱️","Funeral Urn","Objects"],
//        ["🗿","Moai","Objects"],
//        ["🪧","Placard","Objects"],
//        ["🚰","Potable Water","Objects"],
//        ["💘","Heart with Arrow","Symbols"],
//        ["💖","Sparkling Heart","Symbols"],
//        ["💗","Growing Heart","Symbols"],
//        ["💓","Beating Heart","Symbols"],
//        ["💞","Revolving Hearts","Symbols"],
//        ["💕","Two Hearts","Symbols"],
//        ["💟","Heart Decoration","Symbols"],
//        ["❣️","Heart Exclamation","Symbols"],
//        ["💔","Broken Heart","Symbols"],
//        ["❤️‍🔥","Heart on Fire","Symbols"],
//        ["❤️‍🩹","Mending Heart","Symbols"],
//        ["❤️","Red Heart","Symbols"],
//        ["🧡","Orange Heart","Symbols"],
//        ["💛","Yellow Heart","Symbols"],
//        ["💚","Green Heart","Symbols"],
//        ["💙","Blue Heart","Symbols"],
//        ["💜","Purple Heart","Symbols"],
//        ["🤎","Brown Heart","Symbols"],
//        ["🖤","Black Heart","Symbols"],
//        ["🤍","White Heart","Symbols"],
//        ["💯","Hundred Points","Symbols"],
//        ["💢","Anger Symbol","Symbols"],
//        ["💬","Speech Balloon","Symbols"],
//        ["👁️‍🗨️","‍Eye in Speech Bubble","Symbols"],
//        ["🗨","Left Speech Bubble","Symbols"],
//        ["🗯","Right Anger Bubble","Symbols"],
//        ["💭","Thought Balloon","Symbols"],
//        ["💤","Zzz","Symbols"],
//        ["💮","White Flower","Symbols"],
//        ["♨️","Hot Springs","Symbols"],
//        ["💈","Barber Pole","Symbols"],
//        ["🛑","Stop Sign","Symbols"],
//        ["🕛","Twelve O’Clock","Symbols"],
//        ["🕧","Twelve-Thirty, Clock","Symbols"],
//        ["🕐","One O’Clock","Symbols"],
//        ["🕜","One-Thirty, Clock","Symbols"],
//        ["🕑","Two O’Clock","Symbols"],
//        ["🕝","Two-Thirty, Clock","Symbols"],
//        ["🕒","Three O’Clock","Symbols"],
//        ["🕞","Three-Thirty, Clock","Symbols"],
//        ["🕓","Four O’Clock","Symbols"],
//        ["🕟","Four-Thirty, Clock","Symbols"],
//        ["🕔","Five O’Clock","Symbols"],
//        ["🕠","Five-Thirty, Clock","Symbols"],
//        ["🕕","Six O’Clock","Symbols"],
//        ["🕡","Six-Thirty, Clock","Symbols"],
//        ["🕖","Seven O’Clock","Symbols"],
//        ["🕢","Seven-Thirty, Clock","Symbols"],
//        ["🕗","Eight O’Clock","Symbols"],
//        ["🕣","Eight-Thirty, Clock","Symbols"],
//        ["🕘","Nine O’Clock","Symbols"],
//        ["🕤","Nine-Thirty, Clock","Symbols"],
//        ["🕙","Ten O’Clock","Symbols"],
//        ["🕥","Ten-Thirty, Clock","Symbols"],
//        ["🕚","Eleven O’Clock","Symbols"],
//        ["🕦","Eleven-Thirty, Clock","Symbols"],
//        ["🌀","Cyclone, Weather","Symbols"],
//        ["♠️","Spade Suit","Symbols"],
//        ["♥️","Heart Suit","Symbols"],
//        ["♦️","Diamond Suit","Symbols"],
//        ["♣️","Club Suit","Symbols"],
//        ["🃏","Joker","Symbols"],
//        ["🀄","Mahjong Red Dragon","Symbols"],
//        ["🎴","Flower Playing Cards","Symbols"],
//        ["🔇","Muted Speaker","Symbols"],
//        ["🔈","Speaker Low Volume","Symbols"],
//        ["🔉","Speaker Medium Volume","Symbols"],
//        ["🔊","Speaker High Volume","Symbols"],
//        ["📢","Loudspeaker","Symbols"],
//        ["📣","Megaphone","Symbols"],
//        ["📯","Postal Horn","Symbols"],
//        ["🔔","Bell","Symbols"],
//        ["🔕","Bell with Slash","Symbols"],
//        ["🎵","Musical Note","Symbols"],
//        ["🎶","Musical Notes","Symbols"],
//        ["💹","Chart Increasing with Yen","Symbols"],
//        ["🛗","Elevator","Symbols"],
//        ["🏧","ATM Sign","Symbols"],
//        ["🚮","Litter in Bin Sign","Symbols"],
//        ["🚰","Potable Water","Symbols"],
//        ["♿","Wheelchair Symbol","Symbols"],
//        ["🚹","Men’s Room","Symbols"],
//        ["🚺","Women’s Room","Symbols"],
//        ["🚻","Restroom","Symbols"],
//        ["🚼","Baby Symbol","Symbols"],
//        ["🚾","Water Closet","Symbols"],
//        ["⚠️","Warning","Symbols"],
//        ["🚸","Children Crossing","Symbols"],
//        ["⛔","No Entry","Symbols"],
//        ["🚫","Prohibited","Symbols"],
//        ["🚳","No Bicycles","Symbols"],
//        ["🚭","No Smoking","Symbols"],
//        ["🚯","No Littering","Symbols"],
//        ["🚱","Non-Potable Water","Symbols"],
//        ["🚷","No Pedestrians","Symbols"],
//        ["📵","No Mobile Phones","Symbols"],
//        ["🔞","No One Under Eighteen","Symbols"],
//        ["☢️","Radioactive","Symbols"],
//        ["☣️","Biohazard","Symbols"],
//        ["⬆️","Up Arrow","Symbols"],
//        ["↗️","Up-Right Arrow","Symbols"],
//        ["➡️","Right Arrow","Symbols"],
//        ["↘️","Down-Right Arrow","Symbols"],
//        ["⬇️","Down Arrow","Symbols"],
//        ["↙️","Down-Left Arrow","Symbols"],
//        ["⬅️","Left Arrow","Symbols"],
//        ["↖️","Up-Left Arrow","Symbols"],
//        ["↕️","Up-Down Arrow","Symbols"],
//        ["↔️","Left-Right Arrow","Symbols"],
//        ["↩️","Right Arrow Curving Left","Symbols"],
//        ["↪️","Left Arrow Curving Right","Symbols"],
//        ["⤴️","Right Arrow Curving Up","Symbols"],
//        ["⤵️","Right Arrow Curving Down","Symbols"],
//        ["🔃","Clockwise Vertical Arrows","Symbols"],
//        ["🔄","Counterclockwise Arrows Button","Symbols"],
//        ["🔙","Back Arrow","Symbols"],
//        ["🔚","End Arrow","Symbols"],
//        ["🔛","On! Arrow","Symbols"],
//        ["🔜","Soon Arrow","Symbols"],
//        ["🔝","Top Arrow","Symbols"],
//        ["🛐","Place of Worship, Religion","Symbols"],
//        ["⚛️","Atom Symbol, Religion","Symbols"],
//        ["🕉","Om, Religion","Symbols"],
//        ["✡️","Star of David, Religion","Symbols"],
//        ["☸️","Wheel of Dharma, Religion","Symbols"],
//        ["☯️","Yin Yang, Religion","Symbols"],
//        ["✝️","Latin Cross, Religion","Symbols"],
//        ["☦️","Orthodox Cross, Religion","Symbols"],
//        ["☪️","Star and Crescent, Religion","Symbols"],
//        ["☮️","Peace Symbol, Religion","Symbols"],
//        ["🕎","Menorah, Religion","Symbols"],
//        ["🔯","Dotted Six-Pointed Star, Religion","Symbols"],
//        ["♈","Aries, Zodiac","Symbols"],
//        ["♉","Taurus, Zodiac","Symbols"],
//        ["♊","Gemini, Zodiac","Symbols"],
//        ["♋","Cancer, Zodiac","Symbols"],
//        ["♌","Leo, Zodiac","Symbols"],
//        ["♍","Virgo, Zodiac","Symbols"],
//        ["♎","Libra, Zodiac","Symbols"],
//        ["♏","Scorpio, Zodiac","Symbols"],
//        ["♐","Sagittarius, Zodiac","Symbols"],
//        ["♑","Capricorn, Zodiac","Symbols"],
//        ["♒","Aquarius, Zodiac","Symbols"],
//        ["♓","Pisces, Zodiac","Symbols"],
//        ["⛎","Ophiuchus, Zodiac","Symbols"],
//        ["🔀","Shuffle Tracks Button","Symbols"],
//        ["🔁","Repeat Button","Symbols"],
//        ["🔂","Repeat Single Button","Symbols"],
//        ["▶️","Play Button","Symbols"],
//        ["⏩","Fast-Forward Button","Symbols"],
//        ["⏭️","Next Track Button","Symbols"],
//        ["⏯️","Play or Pause Button","Symbols"],
//        ["◀️","Reverse Button","Symbols"],
//        ["⏪","Fast Reverse Button","Symbols"],
//        ["⏮️","Last Track Button","Symbols"],
//        ["🔼","Upwards Button","Symbols"],
//        ["⏫","Fast Up Button","Symbols"],
//        ["🔽","Downwards Button","Symbols"],
//        ["⏬","Fast Down Button","Symbols"],
//        ["⏸️","Pause Button","Symbols"],
//        ["⏹️","Stop Button","Symbols"],
//        ["⏺️","Record Button","Symbols"],
//        ["⏏️","Eject Button","Symbols"],
//        ["🎦","Cinema","Symbols"],
//        ["🔅","Dim Button","Symbols"],
//        ["🔆","Bright Button","Symbols"],
//        ["📶","Antenna Bars","Symbols"],
//        ["📳","Vibration Mode","Symbols"],
//        ["📴","Mobile Phone Off","Symbols"],
//        ["♀️","Female Sign","Symbols"],
//        ["♂️","Male Sign","Symbols"],
//        ["✖️","Multiply, Math","Symbols"],
//        ["➕","Plus, Math","Symbols"],
//        ["➖","Minus, Math","Symbols"],
//        ["➗","Divide, Math","Symbols"],
//        ["♾️","Infinity, Math","Symbols"],
//        ["‼️","Double Exclamation Mark, Punctuation","Symbols"],
//        ["⁉️","Exclamation Question Mark, Punctuation","Symbols"],
//        ["❓","Question Mark, Punctuation","Symbols"],
//        ["❔","White Question Mark, Punctuation","Symbols"],
//        ["❕","White Exclamation Mark, Punctuation","Symbols"],
//        ["❗","Exclamation Mark, Punctuation","Symbols"],
//        ["〰️","Wavy Dash, Punctuation","Symbols"],
//        ["💱","Currency Exchange, Currency","Symbols"],
//        ["💲","Heavy Dollar Sign, Currency","Symbols"],
//        ["⚕️","Medical Symbol","Symbols"],
//        ["♻️","Recycling Symbol","Symbols"],
//        ["⚜️","Fleur-de-lis, Symbol","Symbols"],
//        ["🔱","Trident Emblem, Symbol","Symbols"],
//        ["📛","Name Badge, Symbol","Symbols"],
//        ["🔰","Japanese Symbol for Beginner","Symbols"],
//        ["⭕","Hollow Red Circle, Symbol","Symbols"],
//        ["✅","Check Mark Button, Symbol","Symbols"],
//        ["☑️","Check Box with Check, Symbol","Symbols"],
//        ["✔️","Check Mark, Symbol","Symbols"],
//        ["❌","Cross Mark, Symbol","Symbols"],
//        ["❎","Cross Mark Button, Symbol","Symbols"],
//        ["➰","Curly Loop, Symbol","Symbols"],
//        ["➿","Double Curly Loop, Symbol","Symbols"],
//        ["〽️","Part Alternation Mark, Symbol","Symbols"],
//        ["✳️","Eight-Spoked Asterisk, Symbol","Symbols"],
//        ["✴️","Eight-Pointed Star, Symbol","Symbols"],
//        ["❇️","Sparkle, Symbol","Symbols"],
//        ["©️","Copyright, Symbol","Symbols"],
//        ["®️","Registered, Symbol","Symbols"],
//        ["™️","Trade Mark, Symbol","Symbols"],
//        ["#️⃣","# Number Sign, Keycap","Symbols"],
//        ["*️⃣","* Asterisk, Keycap Number","Symbols"],
//        ["0️⃣","0 Digit Zero, Keycap Number","Symbols"],
//        ["1️⃣","1 Digit One, Keycap Number","Symbols"],
//        ["2️⃣","2 Digit Two, Keycap Number","Symbols"],
//        ["3️⃣","3 Digit Three, Keycap Number","Symbols"],
//        ["4️⃣","4 Digit Four, Keycap Number","Symbols"],
//        ["5️⃣","5 Digit Five, Keycap Number","Symbols"],
//        ["6️⃣","6 Digit Six, Keycap Number","Symbols"],
//        ["7️⃣","7 Digit Seven, Keycap Number","Symbols"],
//        ["8️⃣","8 Digit Eight, Keycap Number","Symbols"],
//        ["9️⃣","9 Digit Nine, Keycap Number","Symbols"],
//        ["🔟","10 Digit Ten, Keycap Number","Symbols"],
//        ["🔠","Input Latin Uppercase, Alphanum","Symbols"],
//        ["🔡","Input Latin Lowercase, Alphanum","Symbols"],
//        ["🔢","Input Numbers, Alphanum","Symbols"],
//        ["🔣","Input Symbols, Alphanum","Symbols"],
//        ["🔤","Input Latin Letters, Alphanum","Symbols"],
//        ["🅰️","A Button Blood Type), Alphanum","Symbols"],
//        ["🆎","AB Button (Blood Type), Alphanum","Symbols"],
//        ["🅱️","B Button (Blood Type), Alphanum","Symbols"],
//        ["🆑","CL Button, Alphanum","Symbols"],
//        ["🆒","Cool Button, Alphanum","Symbols"],
//        ["🆓","Free Button, Alphanum","Symbols"],
//        ["ℹ️","Information, Alphanum","Symbols"],
//        ["🆔","ID Button, Alphanum","Symbols"],
//        ["Ⓜ️","Circled M, Alphanum","Symbols"],
//        ["🆕","New Button, Alphanum","Symbols"],
//        ["🆖","NG Button, Alphanum","Symbols"],
//        ["🅾️","O Button (Blood Type), Alphanum","Symbols"],
//        ["🆗","OK Button, Alphanum","Symbols"],
//        ["🅿️","P Button, Alphanum","Symbols"],
//        ["🆘","SOS Button, Alphanum","Symbols"],
//        ["🆙","Up! Button, Alphanum","Symbols"],
//        ["🆚","Vs Button, Alphanum","Symbols"],
//        ["🈁","Japanese “Here” Button, Alphanum","Symbols"],
//        ["🈂️","Japanese “Service Charge” Button, Alphanum","Symbols"],
//        ["🈷️","Japanese “Monthly Amount” Button, Alphanum","Symbols"],
//        ["🈶","Japanese “Not Free of Charge” Button, Alphanum","Symbols"],
//        ["🈯","Japanese “Reserved” Button, Alphanum","Symbols"],
//        ["🉐","Japanese “Bargain” Button, Alphanum","Symbols"],
//        ["🈹","Japanese “Discount” Button, Alphanum","Symbols"],
//        ["🈚","Japanese “Free of Charge” Button, Alphanum","Symbols"],
//        ["🈲","Japanese “Prohibited” Button, Alphanum","Symbols"],
//        ["🉑","Japanese “Acceptable” Button, Alphanum","Symbols"],
//        ["🈸","Japanese “Application” Button, Alphanum","Symbols"],
//        ["🈴","Japanese “Passing Grade” Button, Alphanum","Symbols"],
//        ["🈳","Japanese “Vacancy” Button, Alphanum","Symbols"],
//        ["㊗️","Japanese “Congratulations” Button, Alphanum","Symbols"],
//        ["㊙️","Japanese “Secret” Button, Alphanum","Symbols"],
//        ["🈺","Japanese “Open for Business” Button, Alphanum","Symbols"],
//        ["🈵","Japanese “No Vacancy” Button, Alphanum","Symbols"],
//        ["🔴","Red Circle, Geometric","Symbols"],
//        ["🟠","Orange Circle, Geometric","Symbols"],
//        ["🟡","Yellow Circle, Geometric","Symbols"],
//        ["🟢","Green Circle, Geometric","Symbols"],
//        ["🔵","Blue Circle, Geometric","Symbols"],
//        ["🟣","Purple Circle, Geometric","Symbols"],
//        ["🟤","Brown Circle, Geometric","Symbols"],
//        ["⚫","Black Circle, Geometric","Symbols"],
//        ["⚪","White Circle, Geometric","Symbols"],
//        ["🟥","Red Square, Geometric","Symbols"],
//        ["🟧","Orange Square, Geometric","Symbols"],
//        ["🟨","Yellow Square, Geometric","Symbols"],
//        ["🟩","Green Square, Geometric","Symbols"],
//        ["🟦","Blue Square, Geometric","Symbols"],
//        ["🟪","Purple Square, Geometric","Symbols"],
//        ["🟫","Brown Square, Geometric","Symbols"],
//        ["⬛","Black Large Square, Geometric","Symbols"],
//        ["⬜","White Large Square, Geometric","Symbols"],
//        ["◼️","Black Medium Square, Geometric","Symbols"],
//        ["◻️","White Medium Square, Geometric","Symbols"],
//        ["◾","Black Medium-Small Square, Geometric","Symbols"],
//        ["◽","White Medium-Small Square, Geometric","Symbols"],
//        ["▪️","Black Small Square, Geometric","Symbols"],
//        ["▫️","White Small Square, Geometric","Symbols"],
//        ["🔶","Large Orange Diamond, Geometric","Symbols"],
//        ["🔷","Large Blue Diamond, Geometric","Symbols"],
//        ["🔸","Small Orange Diamond, Geometric","Symbols"],
//        ["🔹","Small Blue Diamond, Geometric","Symbols"],
//        ["🔺","Red Triangle Pointed Up, Geometric","Symbols"],
//        ["🔻","Red Triangle Pointed Down, Geometric","Symbols"],
//        ["💠","Diamond with a Dot, Geometric","Symbols"],
//        ["🔘","Radio Button, Geometric","Symbols"],
//        ["🔳","White Square Button, Geometric","Symbols"],
//        ["🔲","Black Square Button, Geometric","Symbols"],
//        ["🏁","Chequered, Flag","Flags"],
//        ["🚩","Triangular, Flag","Flags"],
//        ["🎌","Crossed, Flag","Flags"],
//        ["🏴","Black, Flag","Flags"],
//        ["🏳️","White, Flag","Flags"],
//        ["‍🏳️‍🌈","Rainbow, Flag","Flags"],
//        ["🏳️‍⚧️","Transgender, Flag","Flags"],
//        ["🏴‍☠️","Pirate, Flag","Flags"],
//        ["🇦🇨","Ascension Island, Country-flag","Flags"],
//        ["🇦🇩","Andorra, Country-flag","Flags"],
//        ["🇦🇪","United Arab Emirates, Country-flag","Flags"],
//        ["🇦🇫","Afghanistan, Country-flag","Flags"],
//        ["🇦🇬","Antigua & Barbuda, Country-flag","Flags"],
//        ["🇦🇮","Anguilla, Country-flag","Flags"],
//        ["🇦🇱","Albania, Country-flag","Flags"],
//        ["🇦🇲","Armenia, Country-flag","Flags"],
//        ["🇦🇴","Angola, Country-flag","Flags"],
//        ["🇦🇶","Antarctica, Country-flag","Flags"],
//        ["🇦🇷","Argentina, Country-flag","Flags"],
//        ["🇦🇸","American Samoa, Country-flag","Flags"],
//        ["🇦🇹","Austria, Country-flag","Flags"],
//        ["🇦🇺","Australia, Country-flag","Flags"],
//        ["🇦🇼","Aruba, Country-flag","Flags"],
//        ["🇦🇽","Åland Islands, Country-flag","Flags"],
//        ["🇦🇿","Azerbaijan, Country-flag","Flags"],
//        ["🇧🇦","Bosnia & Herzegovina, Country-flag","Flags"],
//        ["🇧🇧","Barbados, Country-flag","Flags"],
//        ["🇧🇩","Bangladesh, Country-flag","Flags"],
//        ["🇧🇪","Belgium, Country-flag","Flags"],
//        ["🇧🇫","Burkina Faso, Country-flag","Flags"],
//        ["🇧🇬","Bulgaria, Country-flag","Flags"],
//        ["🇧🇭","Bahrain, Country-flag","Flags"],
//        ["🇧🇮","Burundi, Country-flag","Flags"],
//        ["🇧🇯","Benin, Country-flag","Flags"],
//        ["🇧🇱","St. Barthélemy, Country-flag","Flags"],
//        ["🇧🇲","Bermuda, Country-flag","Flags"],
//        ["🇧🇳","Brunei, Country-flag","Flags"],
//        ["🇧🇴","Bolivia, Country-flag","Flags"],
//        ["🇧🇶","Caribbean Netherlands, Country-flag","Flags"],
//        ["🇧🇷","Brazil, Country-flag","Flags"],
//        ["🇧🇸","Bahamas, Country-flag","Flags"],
//        ["🇧🇹","Bhutan, Country-flag","Flags"],
//        ["🇧🇻","Bouvet Island, Country-flag","Flags"],
//        ["🇧🇼","Botswana, Country-flag","Flags"],
//        ["🇧🇾","Belarus, Country-flag","Flags"],
//        ["🇧🇿","Belize, Country-flag","Flags"],
//        ["🇨🇦","Canada, Country-flag","Flags"],
//        ["🇨🇨","Cocos (Keeling) Islands, Country-flag","Flags"],
//        ["🇨🇩","Congo - Kinshasa, Country-flag","Flags"],
//        ["🇨🇫","Central African Republic, Country-flag","Flags"],
//        ["🇨🇬","Congo - Brazzaville, Country-flag","Flags"],
//        ["🇨🇭","Switzerland, Country-flag","Flags"],
//        ["🇨🇮","Côte d’Ivoire, Country-flag","Flags"],
//        ["🇨🇰","Cook Islands, Country-flag","Flags"],
//        ["🇨🇱","Chile, Country-flag","Flags"],
//        ["🇨🇲","Cameroon, Country-flag","Flags"],
//        ["🇨🇳","China, Country-flag","Flags"],
//        ["🇨🇴","Colombia, Country-flag","Flags"],
//        ["🇨🇵","Clipperton Island, Country-flag","Flags"],
//        ["🇨🇷","Costa Rica, Country-flag","Flags"],
//        ["🇨🇺","Cuba, Country-flag","Flags"],
//        ["🇨🇻","Cape Verde, Country-flag","Flags"],
//        ["🇨🇼","Curaçao, Country-flag","Flags"],
//        ["🇨🇽","Christmas Island, Country-flag","Flags"],
//        ["🇨🇾","Cyprus, Country-flag","Flags"],
//        ["🇨🇿","Czechia, Country-flag","Flags"],
//        ["🇩🇪","Germany, Country-flag","Flags"],
//        ["🇩🇬","Diego Garcia, Country-flag","Flags"],
//        ["🇩🇯","Djibouti, Country-flag","Flags"],
//        ["🇩🇰","Denmark, Country-flag","Flags"],
//        ["🇩🇲","Dominica, Country-flag","Flags"],
//        ["🇩🇴","Dominican Republic, Country-flag","Flags"],
//        ["🇩🇿","Algeria, Country-flag","Flags"],
//        ["🇪🇦","Ceuta & Melilla, Country-flag","Flags"],
//        ["🇪🇨","Ecuador, Country-flag","Flags"],
//        ["🇪🇪","Estonia, Country-flag","Flags"],
//        ["🇪🇬","Egypt, Country-flag","Flags"],
//        ["🇪🇭","Western Sahara, Country-flag","Flags"],
//        ["🇪🇷","Eritrea, Country-flag","Flags"],
//        ["🇪🇸","Spain, Country-flag","Flags"],
//        ["🇪🇹","Ethiopia, Country-flag","Flags"],
//        ["🇪🇺","European Union, Country-flag","Flags"],
//        ["🇫🇮","Finland, Country-flag","Flags"],
//        ["🇫🇯","Fiji, Country-flag","Flags"],
//        ["🇫🇰","Falkland Islands, Country-flag","Flags"],
//        ["🇫🇲","Micronesia, Country-flag","Flags"],
//        ["🇫🇴","Faroe Islands, Country-flag","Flags"],
//        ["🇫🇷","France, Country-flag","Flags"],
//        ["🇬🇦","Gabon, Country-flag","Flags"],
//        ["🇬🇧","United Kingdom, Country-flag","Flags"],
//        ["🇬🇩","Grenada, Country-flag","Flags"],
//        ["🇬🇪","Georgia, Country-flag","Flags"],
//        ["🇬🇫","French Guiana, Country-flag","Flags"],
//        ["🇬🇬","Guernsey, Country-flag","Flags"],
//        ["🇬🇭","Ghana, Country-flag","Flags"],
//        ["🇬🇮","Gibraltar, Country-flag","Flags"],
//        ["🇬🇱","Greenland, Country-flag","Flags"],
//        ["🇬🇲","Gambia, Country-flag","Flags"],
//        ["🇬🇳","Guinea, Country-flag","Flags"],
//        ["🇬🇵","Guadeloupe, Country-flag","Flags"],
//        ["🇬🇶","Equatorial Guinea, Country-flag","Flags"],
//        ["🇬🇷","Greece, Country-flag","Flags"],
//        ["🇬🇸","South Georgia & South Sandwich Islands, Country-flag","Flags"],
//        ["🇬🇹","Guatemala, Country-flag","Flags"],
//        ["🇬🇺","Guam, Country-flag","Flags"],
//        ["🇬🇼","Guinea-Bissau, Country-flag","Flags"],
//        ["🇬🇾","Guyana, Country-flag","Flags"],
//        ["🇭🇰","Hong Kong SAR China, Country-flag","Flags"],
//        ["🇭🇲","Heard & McDonald Islands, Country-flag","Flags"],
//        ["🇭🇳","Honduras, Country-flag","Flags"],
//        ["🇭🇷","Croatia, Country-flag","Flags"],
//        ["🇭🇹","Haiti, Country-flag","Flags"],
//        ["🇭🇺","Hungary, Country-flag","Flags"],
//        ["🇮🇨","Canary Islands, Country-flag","Flags"],
//        ["🇮🇩","Indonesia, Country-flag","Flags"],
//        ["🇮🇪","Ireland, Country-flag","Flags"],
//        ["🇮🇱","Israel, Country-flag","Flags"],
//        ["🇮🇲","Isle of Man, Country-flag","Flags"],
//        ["🇮🇳","India, Country-flag","Flags"],
//        ["🇮🇴","British Indian Ocean Territory, Country-flag","Flags"],
//        ["🇮🇶","Iraq, Country-flag","Flags"],
//        ["🇮🇷","Iran, Country-flag","Flags"],
//        ["🇮🇸","Iceland, Country-flag","Flags"],
//        ["🇮🇹","Italy, Country-flag","Flags"],
//        ["🇯🇪","Jersey, Country-flag","Flags"],
//        ["🇯🇲","Jamaica, Country-flag","Flags"],
//        ["🇯🇴","Jordan, Country-flag","Flags"],
//        ["🇯🇵","Japan, Country-flag","Flags"],
//        ["🇰🇪","Kenya, Country-flag","Flags"],
//        ["🇰🇬","Kyrgyzstan, Country-flag","Flags"],
//        ["🇰🇭","Cambodia, Country-flag","Flags"],
//        ["🇰🇮","Kiribati, Country-flag","Flags"],
//        ["🇰🇲","Comoros, Country-flag","Flags"],
//        ["🇰🇳","St. Kitts & Nevis, Country-flag","Flags"],
//        ["🇰🇵","North Korea, Country-flag","Flags"],
//        ["🇰🇷","South Korea, Country-flag","Flags"],
//        ["🇰🇼","Kuwait, Country-flag","Flags"],
//        ["🇰🇾","Cayman Islands, Country-flag","Flags"],
//        ["🇰🇿","Kazakhstan, Country-flag","Flags"],
//        ["🇱🇦","Laos, Country-flag","Flags"],
//        ["🇱🇧","Lebanon, Country-flag","Flags"],
//        ["🇱🇨","St. Lucia, Country-flag","Flags"],
//        ["🇱🇮","Liechtenstein, Country-flag","Flags"],
//        ["🇱🇰","Sri Lanka, Country-flag","Flags"],
//        ["🇱🇷","Liberia, Country-flag","Flags"],
//        ["🇱🇸","Lesotho, Country-flag","Flags"],
//        ["🇱🇹","Lithuania, Country-flag","Flags"],
//        ["🇱🇺","Luxembourg, Country-flag","Flags"],
//        ["🇱🇻","Latvia, Country-flag","Flags"],
//        ["🇱🇾","Libya, Country-flag","Flags"],
//        ["🇲🇦","Morocco, Country-flag","Flags"],
//        ["🇲🇨","Monaco, Country-flag","Flags"],
//        ["🇲🇩","Moldova, Country-flag","Flags"],
//        ["🇲🇪","Montenegro, Country-flag","Flags"],
//        ["🇲🇫","St. Martin, Country-flag","Flags"],
//        ["🇲🇬","Madagascar, Country-flag","Flags"],
//        ["🇲🇭","Marshall Islands, Country-flag","Flags"],
//        ["🇲🇰","North Macedonia, Country-flag","Flags"],
//        ["🇲🇱","Mali, Country-flag","Flags"],
//        ["🇲🇲","Myanmar (Burma), Country-flag","Flags"],
//        ["🇲🇳","Mongolia, Country-flag","Flags"],
//        ["🇲🇴","Macao Sar China, Country-flag","Flags"],
//        ["🇲🇵","Northern Mariana Islands, Country-flag","Flags"],
//        ["🇲🇶","Martinique, Country-flag","Flags"],
//        ["🇲🇷","Mauritania, Country-flag","Flags"],
//        ["🇲🇸","Montserrat, Country-flag","Flags"],
//        ["🇲🇹","Malta, Country-flag","Flags"],
//        ["🇲🇺","Mauritius, Country-flag","Flags"],
//        ["🇲🇻","Maldives, Country-flag","Flags"],
//        ["🇲🇼","Malawi, Country-flag","Flags"],
//        ["🇲🇽","Mexico, Country-flag","Flags"],
//        ["🇲🇾","Malaysia, Country-flag","Flags"],
//        ["🇲🇿","Mozambique, Country-flag","Flags"],
//        ["🇳🇦","Namibia, Country-flag","Flags"],
//        ["🇳🇨","New Caledonia, Country-flag","Flags"],
//        ["🇳🇪","Niger, Country-flag","Flags"],
//        ["🇳🇫","Norfolk Island, Country-flag","Flags"],
//        ["🇳🇬","Nigeria, Country-flag","Flags"],
//        ["🇳🇮","Nicaragua, Country-flag","Flags"],
//        ["🇳🇱","Netherlands, Country-flag","Flags"],
//        ["🇳🇴","Norway, Country-flag","Flags"],
//        ["🇳🇵","Nepal, Country-flag","Flags"],
//        ["🇳🇷","Nauru, Country-flag","Flags"],
//        ["🇳🇺","Niue, Country-flag","Flags"],
//        ["🇳🇿","New Zealand, Country-flag","Flags"],
//        ["🇴🇲","Oman, Country-flag","Flags"],
//        ["🇵🇦","Panama, Country-flag","Flags"],
//        ["🇵🇪","Peru, Country-flag","Flags"],
//        ["🇵🇫","French Polynesia, Country-flag","Flags"],
//        ["🇵🇬","Papua New Guinea, Country-flag","Flags"],
//        ["🇵🇭","Philippines, Country-flag","Flags"],
//        ["🇵🇰","Pakistan, Country-flag","Flags"],
//        ["🇵🇱","Poland, Country-flag","Flags"],
//        ["🇵🇲","St. Pierre & Miquelon, Country-flag","Flags"],
//        ["🇵🇳","Pitcairn Islands, Country-flag","Flags"],
//        ["🇵🇷","Puerto Rico, Country-flag","Flags"],
//        ["🇵🇸","Palestinian Territories, Country-flag","Flags"],
//        ["🇵🇹","Portugal, Country-flag","Flags"],
//        ["🇵🇼","Palau, Country-flag","Flags"],
//        ["🇵🇾","Paraguay, Country-flag","Flags"],
//        ["🇶🇦","Qatar, Country-flag","Flags"],
//        ["🇷🇪","Réunion, Country-flag","Flags"],
//        ["🇷🇴","Romania, Country-flag","Flags"],
//        ["🇷🇸","Serbia, Country-flag","Flags"],
//        ["🇷🇺","Russia, Country-flag","Flags"],
//        ["🇷🇼","Rwanda, Country-flag","Flags"],
//        ["🇸🇦","Saudi Arabia, Country-flag","Flags"],
//        ["🇸🇧","Solomon Islands, Country-flag","Flags"],
//        ["🇸🇨","Seychelles, Country-flag","Flags"],
//        ["🇸🇩","Sudan, Country-flag","Flags"],
//        ["🇸🇪","Sweden, Country-flag","Flags"],
//        ["🇸🇬","Singapore, Country-flag","Flags"],
//        ["🇸🇭","St. Helena, Country-flag","Flags"],
//        ["🇸🇮","Slovenia, Country-flag","Flags"],
//        ["🇸🇯","Svalbard & Jan Mayen, Country-flag","Flags"],
//        ["🇸🇰","Slovakia, Country-flag","Flags"],
//        ["🇸🇱","Sierra Leone, Country-flag","Flags"],
//        ["🇸🇲","San Marino, Country-flag","Flags"],
//        ["🇸🇳","Senegal, Country-flag","Flags"],
//        ["🇸🇴","Somalia, Country-flag","Flags"],
//        ["🇸🇷","Suriname, Country-flag","Flags"],
//        ["🇸🇸","South Sudan, Country-flag","Flags"],
//        ["🇸🇹","São Tomé & Príncipe, Country-flag","Flags"],
//        ["🇸🇻","El Salvador, Country-flag","Flags"],
//        ["🇸🇽","Sint Maarten, Country-flag","Flags"],
//        ["🇸🇾","Syria, Country-flag","Flags"],
//        ["🇸🇿","Eswatini, Country-flag","Flags"],
//        ["🇹🇦","Tristan Da Cunha, Country-flag","Flags"],
//        ["🇹🇨","Turks & Caicos Islands, Country-flag","Flags"],
//        ["🇹🇩","Chad, Country-flag","Flags"],
//        ["🇹🇫","French Southern Territories, Country-flag","Flags"],
//        ["🇹🇬","Togo, Country-flag","Flags"],
//        ["🇹🇭","Thailand, Country-flag","Flags"],
//        ["🇹🇯","Tajikistan, Country-flag","Flags"],
//        ["🇹🇰","Tokelau, Country-flag","Flags"],
//        ["🇹🇱","Timor-Leste, Country-flag","Flags"],
//        ["🇹🇲","Turkmenistan, Country-flag","Flags"],
//        ["🇹🇳","Tunisia, Country-flag","Flags"],
//        ["🇹🇴","Tonga, Country-flag","Flags"],
//        ["🇹🇷","Turkey, Country-flag","Flags"],
//        ["🇹🇹","Trinidad & Tobago, Country-flag","Flags"],
//        ["🇹🇻","Tuvalu, Country-flag","Flags"],
//        ["🇹🇼","Taiwan, Country-flag","Flags"],
//        ["🇹🇿","Tanzania, Country-flag","Flags"],
//        ["🇺🇦","Ukraine, Country-flag","Flags"],
//        ["🇺🇬","Uganda, Country-flag","Flags"],
//        ["🇺🇲","U.S. Outlying Islands, Country-flag","Flags"],
//        ["🇺🇳","United Nations, Country-flag","Flags"],
//        ["🇺🇸","United States, Country-flag","Flags"],
//        ["🇺🇾","Uruguay, Country-flag","Flags"],
//        ["🇺🇿","Uzbekistan, Country-flag","Flags"],
//        ["🇻🇦","Vatican City, Country-flag","Flags"],
//        ["🇻🇨","St. Vincent & Grenadines, Country-flag","Flags"],
//        ["🇻🇪","Venezuela, Country-flag","Flags"],
//        ["🇻🇬","British Virgin Islands, Country-flag","Flags"],
//        ["🇻🇮","U.S. Virgin Islands, Country-flag","Flags"],
//        ["🇻🇳","Vietnam, Country-flag","Flags"],
//        ["🇻🇺","Vanuatu, Country-flag","Flags"],
//        ["🇼🇫","Wallis & Futuna, Country-flag","Flags"],
//        ["🇼🇸","Samoa, Country-flag","Flags"],
//        ["🇽🇰","Kosovo, Country-flag","Flags"],
//        ["🇾🇪","Yemen, Country-flag","Flags"],
//        ["🇾🇹","Mayotte, Country-flag","Flags"],
//        ["🇿🇦","South Africa, Country-flag","Flags"],
//        ["🇿🇲","Zambia, Country-flag, Country-flag","Flags"],
//        ["🇿🇼","Zimbabwe, Country-flag, Country-flag","Flags"],
//        ["🏴󠁧󠁢󠁥󠁮󠁧󠁿","England, Subdivision-flag, Country-flag","Flags"],
//        ["🏴󠁧󠁢󠁳󠁣󠁴󠁿","Scotland, Subdivision-flag, Country-flag","Flags"],
//        ["🏴󠁧󠁢󠁷󠁬󠁳󠁿","Wales, Subdivision-flag, Country-flag","Flags"],
//        ["🏴󠁵󠁳󠁴󠁸󠁿","Texas (US-TX), Flag, Country-flag","Flags"]
//    ]
//}
